project('corecrypto', ['c'], meson_version: '>=1.12.0')

srcroot = meson.global_source_root()
buildroot = meson.global_build_root()
gen_dir = buildroot / 'gen'
mig_dir = buildroot / 'mig'
mig_ks_dir = mig_dir / 'ks'
iig_dir = buildroot / 'iig'

target_triple = meson.get_external_property('target_triple', '')
if target_triple == ''
    target_cpu_family = host_machine.cpu_family()
    if target_cpu_family == 'aarch64'
        target_arch = 'arm64'
    elif target_cpu_family == 'x86_64'
        target_arch = 'x86_64'
    else
        target_arch = target_cpu_family
    endif
    target_triple = target_arch + '-apple-macos'
else
    target_arch = target_triple.split('-')[0]
endif

c_sources = files(
    'acceleratecrypto/Source/sha512/sha512_K.c',
    'cc/src/cc_abort.c',
    'cc/src/cc_clear.c',
    'cc/src/cc_cmp_safe.c',
    'cc/src/cc_cpu.c',
    'cc/src/cc_dit.c',
    'cc/src/cc_fault_canary.c',
    'cc/src/cc_impl.c',
    'cc/src/cc_lock.c',
    'cc/src/cc_memory.c',
    'cc/src/cc_rdrand.c',
    'cc/src/cc_timing_safe.c',
    'cc/src/cc_try_abort.c',
    'cc/src/cc_value_barrier.c',
    'cc_fips/fipspost_post_hkdf.c',
    'cc_fips/fipspost_post_mldsa.c',
    'cc_fips/fipspost_post_mlkem.c',
    'cc_fips/src/fipspost_get_hmac.c',
    'cc_fips/src/fipspost_post.c',
    'cc_fips/src/fipspost_post_aes_cbc.c',
    'cc_fips/src/fipspost_post_aes_ccm.c',
    'cc_fips/src/fipspost_post_aes_cmac.c',
    'cc_fips/src/fipspost_post_aes_ecb.c',
    'cc_fips/src/fipspost_post_aes_gcm.c',
    'cc_fips/src/fipspost_post_aes_xts.c',
    'cc_fips/src/fipspost_post_drbg_ctr.c',
    'cc_fips/src/fipspost_post_drbg_hmac.c',
    'cc_fips/src/fipspost_post_ecdh.c',
    'cc_fips/src/fipspost_post_ecdsa.c',
    'cc_fips/src/fipspost_post_hmac.c',
    'cc_fips/src/fipspost_post_kdf_ctr.c',
    'cc_fips/src/fipspost_post_kdf_ctr_cmac.c',
    'cc_fips/src/fipspost_post_pbkdf.c',
    'cc_fips/src/fipspost_post_rsa_sig.c',
    'cc_fips/src/fipspost_trace.c',
    'ccaes/src/arm/ccaes_arm_cbc_decrypt_mode.c',
    'ccaes/src/arm/ccaes_arm_cbc_encrypt_mode.c',
    'ccaes/src/arm/ccaes_arm_cfb_decrypt_mode.c',
    'ccaes/src/arm/ccaes_arm_cfb_encrypt_mode.c',
    'ccaes/src/arm/ccaes_arm_ecb_decrypt_mode.c',
    'ccaes/src/arm/ccaes_arm_ecb_encrypt_mode.c',
    'ccaes/src/arm/ccaes_arm_ofb_crypt_mode.c',
    'ccaes/src/arm/ccaes_arm_xts_decrypt_mode.c',
    'ccaes/src/arm/ccaes_arm_xts_encrypt_mode.c',
    'ccaes/src/ccaes_cbc_decrypt_mode.c',
    'ccaes/src/ccaes_cbc_encrypt_mode.c',
    'ccaes/src/ccaes_ccm_decrypt_mode.c',
    'ccaes/src/ccaes_ccm_encrypt_mode.c',
    'ccaes/src/ccaes_ctr_crypt_mode.c',
    'ccaes/src/ccaes_ecb_decrypt_mode.c',
    'ccaes/src/ccaes_ecb_encrypt_mode.c',
    'ccaes/src/ccaes_gcm_decrypt_mode.c',
    'ccaes/src/ccaes_gcm_encrypt_mode.c',
    'ccaes/src/ccaes_siv_decrypt_mode.c',
    'ccaes/src/ccaes_siv_encrypt_mode.c',
    'ccaes/src/ccaes_siv_hmac_sha256_decrypt_mode.c',
    'ccaes/src/ccaes_siv_hmac_sha256_encrypt_mode.c',
    'ccaes/src/ccaes_xts_decrypt_mode.c',
    'ccaes/src/ccaes_xts_encrypt_mode.c',
    'ccaes/src/gladman/ccaes_gladman_cbc_decrypt.c',
    'ccaes/src/gladman/ccaes_gladman_cbc_encrypt.c',
    'ccaes/src/gladman/ccaes_gladman_crypt.c',
    'ccaes/src/gladman/ccaes_gladman_key.c',
    'ccaes/src/gladman/ccaes_gladman_tab.c',
    'ccaes/src/ltc/ccaes_ltc_common.c',
    'ccaes/src/ltc/ccaes_ltc_ecb_decrypt_mode.c',
    'ccaes/src/ltc/ccaes_ltc_ecb_encrypt_mode.c',
    'ccaes/src/ltc/ccaes_ltc_tab.c',
    'ccaes/src/vng/ccaes_vng_ccm_decrypt.c',
    'ccaes/src/vng/ccaes_vng_ccm_encrypt.c',
    'ccaes/src/vng/ccaes_vng_ctr_crypt.c',
    'ccaes/src/vng/ccaes_vng_gcm_decrypt.c',
    'ccaes/src/vng/ccaes_vng_gcm_encrypt.c',
    'ccansikdf/src/ccansikdf_x963.c',
    'ccasn1/src/ccasn1.c',
    'ccchacha20poly1305/src/ccchacha20poly1305.c',
    'cccmac/src/cccmac_final.c',
    'cccmac/src/cccmac_generate_subkey.c',
    'cccmac/src/cccmac_init.c',
    'cccmac/src/cccmac_one_shot.c',
    'cccmac/src/cccmac_update.c',
    'ccder/src/ccder_blob_compat.c',
    'ccder/src/ccder_blob_decode_bitstring.c',
    'ccder/src/ccder_blob_decode_eckey.c',
    'ccder/src/ccder_blob_decode_len.c',
    'ccder/src/ccder_blob_decode_oid.c',
    'ccder/src/ccder_blob_decode_range.c',
    'ccder/src/ccder_blob_decode_seqii.c',
    'ccder/src/ccder_blob_decode_sequence_tl.c',
    'ccder/src/ccder_blob_decode_tag.c',
    'ccder/src/ccder_blob_decode_tl.c',
    'ccder/src/ccder_blob_decode_uint.c',
    'ccder/src/ccder_blob_decode_uint64.c',
    'ccder/src/ccder_blob_decode_uint_n.c',
    'ccder/src/ccder_blob_encode_body.c',
    'ccder/src/ccder_blob_encode_body_tl.c',
    'ccder/src/ccder_blob_encode_eckey.c',
    'ccder/src/ccder_blob_encode_implicit_integer.c',
    'ccder/src/ccder_blob_encode_implicit_octet_string.c',
    'ccder/src/ccder_blob_encode_implicit_raw_octet_string.c',
    'ccder/src/ccder_blob_encode_implicit_uint64.c',
    'ccder/src/ccder_blob_encode_integer.c',
    'ccder/src/ccder_blob_encode_len.c',
    'ccder/src/ccder_blob_encode_octet_string.c',
    'ccder/src/ccder_blob_encode_oid.c',
    'ccder/src/ccder_blob_encode_raw_octet_string.c',
    'ccder/src/ccder_blob_encode_tag.c',
    'ccder/src/ccder_blob_encode_tl.c',
    'ccder/src/ccder_blob_encode_uint64.c',
    'ccder/src/ccder_blob_reserve.c',
    'ccder/src/ccder_blob_reserve_tl.c',
    'ccder/src/ccder_sizeof.c',
    'ccder/src/ccder_sizeof_eckey.c',
    'ccder/src/ccder_sizeof_implicit_integer.c',
    'ccder/src/ccder_sizeof_implicit_octet_string.c',
    'ccder/src/ccder_sizeof_implicit_raw_octet_string.c',
    'ccder/src/ccder_sizeof_implicit_uint64.c',
    'ccder/src/ccder_sizeof_integer.c',
    'ccder/src/ccder_sizeof_len.c',
    'ccder/src/ccder_sizeof_octet_string.c',
    'ccder/src/ccder_sizeof_oid.c',
    'ccder/src/ccder_sizeof_raw_octet_string.c',
    'ccder/src/ccder_sizeof_tag.c',
    'ccder/src/ccder_sizeof_uint64.c',
    'ccdes/src/ccdes3_ecb_decrypt_mode.c',
    'ccdes/src/ccdes3_ecb_encrypt_mode.c',
    'ccdes/src/ccdes3_ltc_common.c',
    'ccdes/src/ccdes3_ltc_ecb_decrypt.c',
    'ccdes/src/ccdes3_ltc_ecb_encrypt.c',
    'ccdes/src/ccdes_constructed_modes.c',
    'ccdes/src/ccdes_ecb_decrypt_mode.c',
    'ccdes/src/ccdes_ecb_encrypt_mode.c',
    'ccdes/src/ccdes_key.c',
    'ccdes/src/ccdes_ltc_common.c',
    'ccdes/src/ccdes_ltc_ecb_decrypt.c',
    'ccdes/src/ccdes_ltc_ecb_encrypt.c',
    'ccdes/src/ltc_des.c',
    'ccdh/src/ccder_decode_dhparams.c',
    'ccdh/src/ccder_encode_dhparams.c',
    'ccdh/src/ccdh_check_pub.c',
    'ccdh/src/ccdh_common.c',
    'ccdh/src/ccdh_compute_shared_secret.c',
    'ccdh/src/ccdh_copy_gp.c',
    'ccdh/src/ccdh_export_pub.c',
    'ccdh/src/ccdh_generate_key.c',
    'ccdh/src/ccdh_generate_private_key.c',
    'ccdh/src/ccdh_gp_apple768.c',
    'ccdh/src/ccdh_gp_rfc2409group02.c',
    'ccdh/src/ccdh_gp_rfc3526group05.c',
    'ccdh/src/ccdh_gp_rfc3526group14.c',
    'ccdh/src/ccdh_gp_rfc3526group15.c',
    'ccdh/src/ccdh_gp_rfc3526group16.c',
    'ccdh/src/ccdh_gp_rfc3526group17.c',
    'ccdh/src/ccdh_gp_rfc3526group18.c',
    'ccdh/src/ccdh_gp_rfc5114_MODP_1024_160.c',
    'ccdh/src/ccdh_gp_rfc5114_MODP_2048_224.c',
    'ccdh/src/ccdh_gp_rfc5114_MODP_2048_256.c',
    'ccdh/src/ccdh_gp_size.c',
    'ccdh/src/ccdh_import_full.c',
    'ccdh/src/ccdh_import_priv.c',
    'ccdh/src/ccdh_import_pub.c',
    'ccdh/src/ccdh_init_gp.c',
    'ccdh/src/ccdh_init_gp_from_bytes.c',
    'ccdh/src/ccdh_init_gp_with_order.c',
    'ccdh/src/ccdh_lookup_gp.c',
    'ccdh/src/ccdh_pairwise_consistency_check.c',
    'ccdh/src/ccdh_power_blinded.c',
    'ccdh/src/ccdh_ramp_gp_exponent.c',
    'ccdh/src/ccdh_sizeof.c',
    'ccdh/src/ccdh_valid_shared_secret.c',
    'ccdigest/src/ccdigest.c',
    'ccdigest/src/ccdigest_final_64be.c',
    'ccdigest/src/ccdigest_final_64le.c',
    'ccdigest/src/ccdigest_init.c',
    'ccdigest/src/ccdigest_update.c',
    'ccdrbg/src/ccdrbg.c',
    'ccdrbg/src/ccdrbg_df.c',
    'ccdrbg/src/ccdrbg_nistctr.c',
    'ccdrbg/src/ccdrbg_nisthmac.c',
    'ccec/src/ccec_affine_point_from_x.c',
    'ccec/src/ccec_affinify.c',
    'ccec/src/ccec_compact_export.c',
    'ccec/src/ccec_compact_export_pub.c',
    'ccec/src/ccec_compact_generate_key.c',
    'ccec/src/ccec_compact_import_priv.c',
    'ccec/src/ccec_compact_import_pub.c',
    'ccec/src/ccec_compressed_x962_export_pub.c',
    'ccec/src/ccec_compressed_x962_import_pub.c',
    'ccec/src/ccec_compute_key.c',
    'ccec/src/ccec_cp192.c',
    'ccec/src/ccec_cp224.c',
    'ccec/src/ccec_cp224_asm.c',
    'ccec/src/ccec_cp256.c',
    'ccec/src/ccec_cp256_asm.c',
    'ccec/src/ccec_cp384.c',
    'ccec/src/ccec_cp384_asm.c',
    'ccec/src/ccec_cp521.c',
    'ccec/src/ccec_cp_ed25519.c',
    'ccec/src/ccec_cp_ed25519_asm.c',
    'ccec/src/ccec_cp_ed25519_opt.c',
    'ccec/src/ccec_cp_x25519.c',
    'ccec/src/ccec_cp_x25519_asm.c',
    'ccec/src/ccec_cp_x25519_opt.c',
    'ccec/src/ccec_der_export_priv.c',
    'ccec/src/ccec_der_import_priv.c',
    'ccec/src/ccec_double.c',
    'ccec/src/ccec_export_affine_point.c',
    'ccec/src/ccec_export_pub.c',
    'ccec/src/ccec_full_add.c',
    'ccec/src/ccec_full_sub.c',
    'ccec/src/ccec_generate_key.c',
    'ccec/src/ccec_generate_key_deterministic.c',
    'ccec/src/ccec_generate_key_fips.c',
    'ccec/src/ccec_generate_key_internal_fips.c',
    'ccec/src/ccec_generate_key_internal_legacy.c',
    'ccec/src/ccec_generate_key_legacy.c',
    'ccec/src/ccec_generate_scalar_fips_extrabits.c',
    'ccec/src/ccec_generate_scalar_fips_retry.c',
    'ccec/src/ccec_generate_scalar_legacy.c',
    'ccec/src/ccec_get_cp.c',
    'ccec/src/ccec_get_fullkey_components.c',
    'ccec/src/ccec_get_pubkey_components.c',
    'ccec/src/ccec_import_affine_point.c',
    'ccec/src/ccec_import_pub.c',
    'ccec/src/ccec_is_point.c',
    'ccec/src/ccec_make_priv.c',
    'ccec/src/ccec_make_pub.c',
    'ccec/src/ccec_make_pub_from_priv.c',
    'ccec/src/ccec_mult.c',
    'ccec/src/ccec_mult_blinded.c',
    'ccec/src/ccec_pairwise_consistency_check.c',
    'ccec/src/ccec_projectify.c',
    'ccec/src/ccec_raw_import.c',
    'ccec/src/ccec_sign.c',
    'ccec/src/ccec_sign_composite.c',
    'ccec/src/ccec_sign_internal.c',
    'ccec/src/ccec_signature_r_s_size.c',
    'ccec/src/ccec_sizeof.c',
    'ccec/src/ccec_twin_mult.c',
    'ccec/src/ccec_validate_point_and_projectify.c',
    'ccec/src/ccec_validate_pub.c',
    'ccec/src/ccec_validate_scalar.c',
    'ccec/src/ccec_verify.c',
    'ccec/src/ccec_verify_composite.c',
    'ccec/src/ccec_verify_internal.c',
    'ccec/src/ccec_x963_export.c',
    'ccec/src/ccec_x963_import_priv.c',
    'ccec/src/ccec_x963_import_pub.c',
    'ccec/src/ccecdh_compute_shared_secret.c',
    'ccec/src/ccecdh_generate_key.c',
    'ccec/src/ccecdh_pairwise_consistency_check.c',
    'ccec25519/src/ccec25519_shared.c',
    'ccec25519/src/cced25519.c',
    'ccec25519/src/cced25519_eddsa.c',
    'ccec25519/src/cced25519_make_key_pair.c',
    'ccec25519/src/cced25519_scalar_mult.c',
    'ccec25519/src/cced25519_sign.c',
    'ccec25519/src/cced25519_verify.c',
    'ccec25519/src/curve25519.c',
    'ccec25519/src/shared25519.c',
    'ccecies/src/ccecies_decrypt_gcm.c',
    'ccecies/src/ccecies_decrypt_gcm_decrypt.c',
    'ccecies/src/ccecies_decrypt_gcm_from_shared_secret.c',
    'ccecies/src/ccecies_decrypt_gcm_plaintext_size.c',
    'ccecies/src/ccecies_decrypt_gcm_setup.c',
    'ccecies/src/ccecies_encrypt_gcm.c',
    'ccecies/src/ccecies_encrypt_gcm_ciphertext_size.c',
    'ccecies/src/ccecies_encrypt_gcm_derive_key.c',
    'ccecies/src/ccecies_encrypt_gcm_encrypt.c',
    'ccecies/src/ccecies_encrypt_gcm_from_shared_secret.c',
    'ccecies/src/ccecies_encrypt_gcm_setup.c',
    'ccecies/src/ccecies_export_eph_pub.c',
    'ccecies/src/ccecies_import_eph_pub.c',
    'ccecies/src/ccecies_pub_key_size.c',
    'ccentropy/src/ccentropy.c',
    'ccentropy/src/ccentropy_digest.c',
    'ccentropy/src/ccentropy_list.c',
    'ccentropy/src/ccentropy_lock.c',
    'ccentropy/src/ccentropy_rng.c',
    'cchkdf/src/cchkdf.c',
    'cchmac/src/cchmac.c',
    'cchmac/src/cchmac_final.c',
    'cchmac/src/cchmac_init.c',
    'cchmac/src/cchmac_update.c',
    'cckeccak/src/cckeccak.c',
    'cckeccak/src/ccshake.c',
    'cckeccak/src/ccshake128_xi.c',
    'cckeccak/src/ccshake256_xi.c',
    'cckem/src/cckem.c',
    'cckem/src/cckem_ctx.c',
    'cckprng/src/cckprng_generate.c',
    'cckprng/src/cckprng_init.c',
    'cckprng/src/cckprng_initgen.c',
    'cckprng/src/cckprng_refresh.c',
    'cckprng/src/cckprng_reseed.c',
    'cckyber/src/cckem_kyber1024.c',
    'cckyber/src/cckem_kyber768.c',
    'ccmd4/src/ccmd4_initial_state.c',
    'ccmd5/src/ccmd5.c',
    'ccmd5/src/ccmd5_ltc.c',
    'ccmldsa/src/ccmldsa_ctx.c',
    'ccmldsa/src/ccmldsa_keygen.c',
    'ccmldsa/src/ccmldsa_ntt.c',
    'ccmldsa/src/ccmldsa_params.c',
    'ccmldsa/src/ccmldsa_poly.c',
    'ccmldsa/src/ccmldsa_polyvec.c',
    'ccmldsa/src/ccmldsa_sample.c',
    'ccmldsa/src/ccmldsa_shared.c',
    'ccmldsa/src/ccmldsa_sign.c',
    'ccmldsa/src/ccmldsa_verify.c',
    'ccmlkem/src/cckem_mlkem1024.c',
    'ccmlkem/src/cckem_mlkem768.c',
    'ccmlkem/src/ccmlkem_compress.c',
    'ccmlkem/src/ccmlkem_indcpa.c',
    'ccmlkem/src/ccmlkem_kem.c',
    'ccmlkem/src/ccmlkem_ntt.c',
    'ccmlkem/src/ccmlkem_poly.c',
    'ccmlkem/src/ccmlkem_polyvec.c',
    'ccmlkem/src/ccmlkem_sample.c',
    'ccmlkem/src/ccmlkem_symmetric.c',
    'ccmode/src/cccbc.c',
    'ccmode/src/ccccm.c',
    'ccmode/src/cccfb.c',
    'ccmode/src/cccfb8.c',
    'ccmode/src/ccctr.c',
    'ccmode/src/ccecb.c',
    'ccmode/src/ccgcm.c',
    'ccmode/src/ccmode_cbc_decrypt.c',
    'ccmode/src/ccmode_cbc_encrypt.c',
    'ccmode/src/ccmode_cbc_init.c',
    'ccmode/src/ccmode_ccm_cbcmac.c',
    'ccmode/src/ccmode_ccm_decrypt.c',
    'ccmode/src/ccmode_ccm_encrypt.c',
    'ccmode/src/ccmode_ccm_finalize.c',
    'ccmode/src/ccmode_ccm_init.c',
    'ccmode/src/ccmode_ccm_reset.c',
    'ccmode/src/ccmode_ccm_set_iv.c',
    'ccmode/src/ccmode_cfb8_decrypt.c',
    'ccmode/src/ccmode_cfb8_encrypt.c',
    'ccmode/src/ccmode_cfb8_init.c',
    'ccmode/src/ccmode_cfb_decrypt.c',
    'ccmode/src/ccmode_cfb_encrypt.c',
    'ccmode/src/ccmode_cfb_init.c',
    'ccmode/src/ccmode_ctr_crypt.c',
    'ccmode/src/ccmode_ctr_init.c',
    'ccmode/src/ccmode_ctr_setctr.c',
    'ccmode/src/ccmode_factory_cbc_decrypt.c',
    'ccmode/src/ccmode_factory_cbc_encrypt.c',
    'ccmode/src/ccmode_factory_ccm_decrypt.c',
    'ccmode/src/ccmode_factory_ccm_encrypt.c',
    'ccmode/src/ccmode_factory_cfb8_decrypt.c',
    'ccmode/src/ccmode_factory_cfb8_encrypt.c',
    'ccmode/src/ccmode_factory_cfb_decrypt.c',
    'ccmode/src/ccmode_factory_cfb_encrypt.c',
    'ccmode/src/ccmode_factory_ctr_crypt.c',
    'ccmode/src/ccmode_factory_gcm_decrypt.c',
    'ccmode/src/ccmode_factory_gcm_encrypt.c',
    'ccmode/src/ccmode_factory_ofb_crypt.c',
    'ccmode/src/ccmode_factory_siv_decrypt.c',
    'ccmode/src/ccmode_factory_siv_encrypt.c',
    'ccmode/src/ccmode_factory_siv_hmac_decrypt.c',
    'ccmode/src/ccmode_factory_siv_hmac_encrypt.c',
    'ccmode/src/ccmode_factory_xts_decrypt.c',
    'ccmode/src/ccmode_factory_xts_encrypt.c',
    'ccmode/src/ccmode_gcm_aad.c',
    'ccmode/src/ccmode_gcm_decrypt.c',
    'ccmode/src/ccmode_gcm_encrypt.c',
    'ccmode/src/ccmode_gcm_finalize.c',
    'ccmode/src/ccmode_gcm_gf_mult.c',
    'ccmode/src/ccmode_gcm_init.c',
    'ccmode/src/ccmode_gcm_mult_h.c',
    'ccmode/src/ccmode_gcm_reset.c',
    'ccmode/src/ccmode_gcm_set_iv.c',
    'ccmode/src/ccmode_ofb_crypt.c',
    'ccmode/src/ccmode_ofb_init.c',
    'ccmode/src/ccmode_siv_auth.c',
    'ccmode/src/ccmode_siv_decrypt.c',
    'ccmode/src/ccmode_siv_encrypt.c',
    'ccmode/src/ccmode_siv_hmac_auth.c',
    'ccmode/src/ccmode_siv_hmac_decrypt.c',
    'ccmode/src/ccmode_siv_hmac_encrypt.c',
    'ccmode/src/ccmode_siv_hmac_init.c',
    'ccmode/src/ccmode_siv_hmac_nonce.c',
    'ccmode/src/ccmode_siv_hmac_reset.c',
    'ccmode/src/ccmode_siv_hmac_temp_key_gen.c',
    'ccmode/src/ccmode_siv_init.c',
    'ccmode/src/ccmode_siv_reset.c',
    'ccmode/src/ccmode_xts_crypt.c',
    'ccmode/src/ccmode_xts_init.c',
    'ccmode/src/ccmode_xts_key_sched.c',
    'ccmode/src/ccmode_xts_mult_alpha.c',
    'ccmode/src/ccmode_xts_set_tweak.c',
    'ccmode/src/ccofb.c',
    'ccmode/src/ccsiv.c',
    'ccmode/src/ccsiv_hmac.c',
    'ccmode/src/ccxts.c',
    'ccn/src/ccn_abs.c',
    'ccn/src/ccn_add.c',
    'ccn/src/ccn_add1.c',
    'ccn/src/ccn_addmul1.c',
    'ccn/src/ccn_addn.c',
    'ccn/src/ccn_bitlen.c',
    'ccn/src/ccn_cmp.c',
    'ccn/src/ccn_cmpn.c',
    'ccn/src/ccn_common.c',
    'ccn/src/ccn_cond_add.c',
    'ccn/src/ccn_cond_clear.c',
    'ccn/src/ccn_cond_neg.c',
    'ccn/src/ccn_cond_rsub.c',
    'ccn/src/ccn_cond_shift_right.c',
    'ccn/src/ccn_cond_sub.c',
    'ccn/src/ccn_cond_swap.c',
    'ccn/src/ccn_div_exact.c',
    'ccn/src/ccn_divides1.c',
    'ccn/src/ccn_divmod.c',
    'ccn/src/ccn_gcd.c',
    'ccn/src/ccn_invmod.c',
    'ccn/src/ccn_lcm.c',
    'ccn/src/ccn_mul.c',
    'ccn/src/ccn_mul1.c',
    'ccn/src/ccn_muln.c',
    'ccn/src/ccn_mux.c',
    'ccn/src/ccn_n.c',
    'ccn/src/ccn_neg.c',
    'ccn/src/ccn_random_bits.c',
    'ccn/src/ccn_read_uint.c',
    'ccn/src/ccn_recode_jsf.c',
    'ccn/src/ccn_recode_ssw.c',
    'ccn/src/ccn_set.c',
    'ccn/src/ccn_shift_left.c',
    'ccn/src/ccn_shift_left_multi.c',
    'ccn/src/ccn_shift_right.c',
    'ccn/src/ccn_shift_right_multi.c',
    'ccn/src/ccn_sizeof.c',
    'ccn/src/ccn_sqr.c',
    'ccn/src/ccn_sub.c',
    'ccn/src/ccn_sub1.c',
    'ccn/src/ccn_subn.c',
    'ccn/src/ccn_trailing_zeros.c',
    'ccn/src/ccn_write_int.c',
    'ccn/src/ccn_write_uint.c',
    'ccn/src/ccn_zero_multi.c',
    'ccnistkdf/src/ccnistkdf_ctr_cmac.c',
    'ccnistkdf/src/ccnistkdf_ctr_hmac.c',
    'ccpad/src/ccpad_cts1_decrypt.c',
    'ccpad/src/ccpad_cts1_encrypt.c',
    'ccpad/src/ccpad_cts2_decrypt.c',
    'ccpad/src/ccpad_cts2_encrypt.c',
    'ccpad/src/ccpad_cts3_decrypt.c',
    'ccpad/src/ccpad_cts3_encrypt.c',
    'ccpad/src/ccpad_pkcs7_decrypt.c',
    'ccpad/src/ccpad_pkcs7_ecb_decrypt.c',
    'ccpad/src/ccpad_pkcs7_ecb_encrypt.c',
    'ccpad/src/ccpad_pkcs7_encrypt.c',
    'ccpad/src/ccpad_pkcs7_padding_decode.c',
    'ccpad/src/ccpad_xts_decrypt.c',
    'ccpad/src/ccpad_xts_encrypt.c',
    'ccpbkdf2/src/ccpbkdf2_hmac.c',
    'ccprime/src/ccprime_rabin_miller.c',
    'ccrc4/src/ccrc4.c',
    'ccrc4/src/ccrc4_eay.c',
    'ccrng/src/ccrng_crypto.c',
    'ccrng/src/ccrng_drbg.c',
    'ccrng/src/ccrng_ecfips_test.c',
    'ccrng/src/ccrng_entropy.c',
    'ccrng/src/ccrng_fortuna.c',
    'ccrng/src/ccrng_process.c',
    'ccrng/src/ccrng_rdrand.c',
    'ccrng/src/ccrng_rsafips_test.c',
    'ccrng/src/ccrng_schedule.c',
    'ccrng/src/ccrng_sequence.c',
    'ccrng/src/ccrng_system.c',
    'ccrng/src/ccrng_uniform.c',
    'ccrng/src/ccrng_zero.c',
    'ccrsa/src/ccder_decode_rsa_priv.c',
    'ccrsa/src/ccder_decode_rsa_priv_n.c',
    'ccrsa/src/ccder_decode_rsa_pub.c',
    'ccrsa/src/ccder_decode_rsa_pub_n.c',
    'ccrsa/src/ccder_decode_rsa_pub_x509.c',
    'ccrsa/src/ccder_decode_rsa_pub_x509_n.c',
    'ccrsa/src/ccder_encode_rsa_priv.c',
    'ccrsa/src/ccder_encode_rsa_priv_size.c',
    'ccrsa/src/ccder_encode_rsa_pub.c',
    'ccrsa/src/ccder_encode_rsa_pub_size.c',
    'ccrsa/src/ccmgf.c',
    'ccrsa/src/ccrsa_common.c',
    'ccrsa/src/ccrsa_crt_makekey.c',
    'ccrsa/src/ccrsa_decrypt_eme_pkcs1v15.c',
    'ccrsa/src/ccrsa_decrypt_eme_pkcs1v15_blinded.c',
    'ccrsa/src/ccrsa_decrypt_oaep.c',
    'ccrsa/src/ccrsa_decrypt_oaep_blinded.c',
    'ccrsa/src/ccrsa_eme_pkcs1v15_decode.c',
    'ccrsa/src/ccrsa_eme_pkcs1v15_encode.c',
    'ccrsa/src/ccrsa_emsa_pkcs1v15_encode.c',
    'ccrsa/src/ccrsa_emsa_pkcs1v15_verify.c',
    'ccrsa/src/ccrsa_emsa_pss_decode.c',
    'ccrsa/src/ccrsa_emsa_pss_encode.c',
    'ccrsa/src/ccrsa_encrypt_oaep.c',
    'ccrsa/src/ccrsa_export_pub.c',
    'ccrsa/src/ccrsa_generate_fips186_key.c',
    'ccrsa/src/ccrsa_get_fullkey_components.c',
    'ccrsa/src/ccrsa_get_pubkey_components.c',
    'ccrsa/src/ccrsa_import_priv.c',
    'ccrsa/src/ccrsa_import_pub.c',
    'ccrsa/src/ccrsa_init_pub.c',
    'ccrsa/src/ccrsa_is_valid_prime.c',
    'ccrsa/src/ccrsa_make_priv.c',
    'ccrsa/src/ccrsa_make_pub.c',
    'ccrsa/src/ccrsa_num_mr_iterations.c',
    'ccrsa/src/ccrsa_oaep_decode.c',
    'ccrsa/src/ccrsa_oaep_encode.c',
    'ccrsa/src/ccrsa_pairwise_consistency_check.c',
    'ccrsa/src/ccrsa_priv_crypt.c',
    'ccrsa/src/ccrsa_priv_crypt_blinded.c',
    'ccrsa/src/ccrsa_pub_crypt.c',
    'ccrsa/src/ccrsa_pubkeylength.c',
    'ccrsa/src/ccrsa_sign_pkcs1v15.c',
    'ccrsa/src/ccrsa_sign_pss.c',
    'ccrsa/src/ccrsa_sign_pss_blinded.c',
    'ccrsa/src/ccrsa_sizeof.c',
    'ccrsa/src/ccrsa_verify_pkcs1v15.c',
    'ccrsa/src/ccrsa_verify_pkcs1v15_allowshortsigs.c',
    'ccrsa/src/ccrsa_verify_pkcs1v15_internal.c',
    'ccrsa/src/ccrsa_verify_pss.c',
    'ccscrypt/src/ccscrypt.c',
    'ccsha1/src/ccsha1.c',
    'ccsha1/src/ccsha1_initial_state.c',
    'ccsha1/src/ccsha1_ltc.c',
    'ccsha1/src/ccsha1_vng_arm.c',
    'ccsha2/src/ccsha224_di.c',
    'ccsha2/src/ccsha224_initial_state.c',
    'ccsha2/src/ccsha224_ltc_di.c',
    'ccsha2/src/ccsha224_vng_arm_di.c',
    'ccsha2/src/ccsha256_K.c',
    'ccsha2/src/ccsha256_di.c',
    'ccsha2/src/ccsha256_initial_state.c',
    'ccsha2/src/ccsha256_ltc_compress.c',
    'ccsha2/src/ccsha256_ltc_di.c',
    'ccsha2/src/ccsha256_vng_arm_di.c',
    'ccsha2/src/ccsha384_di.c',
    'ccsha2/src/ccsha384_initial_state.c',
    'ccsha2/src/ccsha384_ltc_di.c',
    'ccsha2/src/ccsha384_vng_arm_di.c',
    'ccsha2/src/ccsha384_vng_arm_hw_di.c',
    'ccsha2/src/ccsha512_256_di.c',
    'ccsha2/src/ccsha512_256_initial_state.c',
    'ccsha2/src/ccsha512_256_ltc_di.c',
    'ccsha2/src/ccsha512_256_vng_arm_di.c',
    'ccsha2/src/ccsha512_256_vng_arm_hw_di.c',
    'ccsha2/src/ccsha512_K.c',
    'ccsha2/src/ccsha512_di.c',
    'ccsha2/src/ccsha512_initial_state.c',
    'ccsha2/src/ccsha512_ltc_compress.c',
    'ccsha2/src/ccsha512_ltc_di.c',
    'ccsha2/src/ccsha512_vng_arm_di.c',
    'ccsha2/src/ccsha512_vng_arm_hw_di.c',
    'ccsha3/src/ccsha3_224_di.c',
    'ccsha3/src/ccsha3_256_di.c',
    'ccsha3/src/ccsha3_384_di.c',
    'ccsha3/src/ccsha3_512_di.c',
    'ccsha3/src/ccsha3_final.c',
    'ccsha3/src/ccsha3_initial_state.c',
    'ccsrp/src/ccsrp.c',
    'ccsrp/src/ccsrp_client.c',
    'ccsrp/src/ccsrp_common.c',
    'ccsrp/src/ccsrp_digest.c',
    'ccsrp/src/ccsrp_generate_H_AMK.c',
    'ccsrp/src/ccsrp_generate_K_from_S.c',
    'ccsrp/src/ccsrp_generate_M.c',
    'ccsrp/src/ccsrp_generate_salt_and_verification.c',
    'ccsrp/src/ccsrp_generate_x.c',
    'ccsrp/src/ccsrp_gp_rfc5054_1024.c',
    'ccsrp/src/ccsrp_gp_rfc5054_2048.c',
    'ccsrp/src/ccsrp_gp_rfc5054_3072.c',
    'ccsrp/src/ccsrp_gp_rfc5054_4096.c',
    'ccsrp/src/ccsrp_gp_rfc5054_8192.c',
    'ccsrp/src/ccsrp_server.c',
    'ccwrap/src/ccwrap_argsvalid.c',
    'ccwrap/src/ccwrap_auth_decrypt.c',
    'ccwrap/src/ccwrap_auth_decrypt_withiv.c',
    'ccwrap/src/ccwrap_auth_encrypt.c',
    'ccwrap/src/ccwrap_auth_encrypt_withiv.c',
    'ccwrap/src/ccwrap_unwrapped_size.c',
    'ccwrap/src/ccwrap_wrapped_size.c',
    'ccxof/src/ccxof.c',
    'ccxwing/src/cckem_xwing_mlkem768x25519.c',
    'cczp/src/cczp_add.c',
    'cczp/src/cczp_common.c',
    'cczp/src/cczp_div2.c',
    'cczp/src/cczp_from.c',
    'cczp/src/cczp_funcs.c',
    'cczp/src/cczp_generate_non_zero_element.c',
    'cczp/src/cczp_generate_random_element.c',
    'cczp/src/cczp_init.c',
    'cczp/src/cczp_inv.c',
    'cczp/src/cczp_inv_field.c',
    'cczp/src/cczp_is_quadratic_residue.c',
    'cczp/src/cczp_mm.c',
    'cczp/src/cczp_mm_redc.c',
    'cczp/src/cczp_mod.c',
    'cczp/src/cczp_mul.c',
    'cczp/src/cczp_negate.c',
    'cczp/src/cczp_power.c',
    'cczp/src/cczp_power_blinded.c',
    'cczp/src/cczp_power_fast.c',
    'cczp/src/cczp_prime.c',
    'cczp/src/cczp_sizeof.c',
    'cczp/src/cczp_sqr.c',
    'cczp/src/cczp_sqrt.c',
    'cczp/src/cczp_sub.c',
    'cczp/src/cczp_to.c',
    'corecrypto_kext/corecrypto_kext.c',
)
s_sources = files(
    'acceleratecrypto/Source/aes/arm/decrypt.s',
    'acceleratecrypto/Source/aes/arm/encrypt.s',
    'acceleratecrypto/Source/aes/arm64/aes_key_schedule.S',
    'acceleratecrypto/Source/aes/arm64/decrypt.s',
    'acceleratecrypto/Source/aes/arm64/decrypt_ecb.s',
    'acceleratecrypto/Source/aes/arm64/encrypt.s',
    'acceleratecrypto/Source/aes/arm64/encrypt_ecb.s',
    'acceleratecrypto/Source/ml-kem/arm64/compress.s',
    'acceleratecrypto/Source/ml-kem/arm64/decompress.s',
    'acceleratecrypto/Source/ml-kem/arm64/ntt_forward.s',
    'acceleratecrypto/Source/ml-kem/arm64/ntt_inverse.s',
    'acceleratecrypto/Source/ml-kem/arm64/poly.s',
    'acceleratecrypto/Source/sha1/arm64/sha1_compress_arm64.s',
    'acceleratecrypto/Source/sha256/arm64/sha256_compress_arm64.s',
    'acceleratecrypto/Source/sha256/arm64/sha256_compress_arm64neon.s',
    'acceleratecrypto/Source/sha3/arm64/sha3_keccak_arm64.s',
    'acceleratecrypto/Source/sha3/arm64/sha3_keccak_arm64hw.s',
    'acceleratecrypto/Source/sha512/arm64/sha512_compress_arm64.s',
    'acceleratecrypto/Source/sha512/arm64/sha512_compress_arm64hw.s',
    'ccaes/src/arm/aesdata.s',
    'ccaes/src/arm/aesdecbc.s',
    'ccaes/src/arm/aesencbc.s',
    'ccaes/src/arm/aeskey.s',
    'ccaes/src/arm/ccaes_arm_xts_decrypt.s',
    'ccaes/src/arm/ccaes_arm_xts_encrypt.s',
    'ccaes/src/arm/cfb-decrypt.s',
    'ccaes/src/arm/cfb-encrypt.s',
    'ccaes/src/arm/ctr-crypt.s',
    'ccaes/src/arm/ofb-crypt.s',
    'ccaes/src/arm64/ccm-decrypt.s',
    'ccaes/src/arm64/ccm-encrypt.s',
    'ccaes/src/arm64/cfb-decrypt-arm64.s',
    'ccaes/src/arm64/cfb-encrypt-arm64.s',
    'ccaes/src/arm64/ctr-arm64.s',
    'ccaes/src/arm64/gcm-arm64.s',
    'ccaes/src/arm64/ghash-arm64.s',
    'ccaes/src/arm64/ofb-crypt-arm64.s',
    'ccn/src/arm/ccn_add.s',
    'ccn/src/arm/ccn_add1-arm64.s',
    'ccn/src/arm/ccn_addmul1-arm64.s',
    'ccn/src/arm/ccn_cmp-arm64.s',
    'ccn/src/arm/ccn_cmp.s',
    'ccn/src/arm/ccn_mul.s',
    'ccn/src/arm/ccn_mul1-arm64.s',
    'ccn/src/arm/ccn_mulmod_p224-arm64.s',
    'ccn/src/arm/ccn_mulmod_p25519-arm64.s',
    'ccn/src/arm/ccn_mulmod_p256-arm64.s',
    'ccn/src/arm/ccn_mulmod_p384-arm64.s',
    'ccn/src/arm/ccn_n-arm64.s',
    'ccn/src/arm/ccn_n.s',
    'ccn/src/arm/ccn_set.s',
    'ccn/src/arm/ccn_shift_left_arm64.s',
    'ccn/src/arm/ccn_shift_right.s',
    'ccn/src/arm/ccn_sub.s',
    'ccn/src/arm/ccn_sub1.s',
)

cc_includes = []
foreach inc : [
    'acceleratecrypto/Include',
    'acceleratecrypto/Header',
    'corecrypto_static',
    'ccdigest',
    'ccdigest/src',
    'ccdigest/corecrypto',
    'ccchacha20poly1305',
    'ccchacha20poly1305/src',
    'ccchacha20poly1305/corecrypto',
    'ccsha1',
    'ccsha1/src',
    'ccsha1/corecrypto',
    'cckem',
    'cckem/src',
    'cckem/corecrypto',
    'ccmlkem',
    'ccmlkem/src',
    'ccmlkem/corecrypto',
    'ccsigma',
    'ccsigma/src',
    'ccsigma/corecrypto',
    'ccec',
    'ccec/src',
    'ccec/corecrypto',
    'ccpad',
    'ccpad/src',
    'ccpad/corecrypto',
    'ccxwing',
    'ccxwing/src',
    'ccxwing/corecrypto',
    'ccentropy',
    'ccentropy/src',
    'ccentropy/corecrypto',
    'ccmldsa',
    'ccmldsa/src',
    'ccmldsa/corecrypto',
    'ccnistkdf',
    'ccnistkdf/src',
    'ccnistkdf/corecrypto',
    'cchkdf',
    'cchkdf/src',
    'cchkdf/corecrypto',
    'prng_seedctl',
    'cckeccak',
    'cckeccak/src',
    'cckeccak/corecrypto',
    'ccrsa',
    'ccrsa/src',
    'ccrsa/corecrypto',
    'ccwrap',
    'ccwrap/src',
    'ccwrap/corecrypto',
    'corecrypto_dylib',
    'config',
    'cckyber',
    'cckyber/src',
    'cckyber/corecrypto',
    'ccsae',
    'ccsae/src',
    'ccsae/corecrypto',
    'cchpke',
    'cchpke/src',
    'cchpke/corecrypto',
    'ccdes',
    'ccdes/src',
    'ccdes/corecrypto',
    'ccder',
    'ccder/src',
    'ccder/corecrypto',
    'corecrypto_rtkit',
    'cczp',
    'cczp/src',
    'cczp/corecrypto',
    'ccmd4',
    'ccmd4/src',
    'ccmd4/corecrypto',
    'ccrc2',
    'ccrc2/src',
    'ccrc2/corecrypto',
    'cche',
    'cche/src',
    'cche/corecrypto',
    'ccckg',
    'ccckg/src',
    'ccckg/corecrypto',
    'corecrypto.xcodeproj',
    'ccmd2',
    'ccmd2/src',
    'ccmd2/corecrypto',
    'ccxof',
    'ccxof/src',
    'ccxof/corecrypto',
    'ccmd5',
    'ccmd5/src',
    'ccmd5/corecrypto',
    'ccpbkdf2',
    'ccpbkdf2/src',
    'ccpbkdf2/corecrypto',
    'ccprime',
    'ccprime/src',
    'ccprime/corecrypto',
    'cc_fips',
    'cc_fips/src',
    'cc_fips/corecrypto',
    'ccrc4',
    'ccrc4/src',
    'ccrc4/corecrypto',
    'ccdh',
    'ccdh/src',
    'ccdh/corecrypto',
    'ccsha2',
    'ccsha2/src',
    'ccsha2/src/arm',
    'ccsha2/corecrypto',
    'corecrypto_kext',
    'ccsrp',
    'ccsrp/src',
    'ccsrp/corecrypto',
    'ccscrypt',
    'ccscrypt/src',
    'ccscrypt/corecrypto',
    'ccblowfish',
    'ccblowfish/src',
    'ccblowfish/corecrypto',
    'cclr',
    'cclr/src',
    'cclr/corecrypto',
    'ccmode',
    'ccmode/src',
    'ccmode/corecrypto',
    'ccrng',
    'ccrng/src',
    'ccrng/corecrypto',
    'ccsha3',
    'ccsha3/src',
    'ccsha3/corecrypto',
    'ccaes',
    'ccaes/src',
    'ccaes/src/arm',
    'ccaes/corecrypto',
    'ccpolyzp_po2cyc',
    'ccpolyzp_po2cyc/src',
    'ccpolyzp_po2cyc/corecrypto',
    'ccecies',
    'ccecies/src',
    'ccecies/corecrypto',
    'ccspake',
    'ccspake/src',
    'ccspake/corecrypto',
    'hmacfiletool',
    'cchmac',
    'cchmac/src',
    'cchmac/corecrypto',
    'ccripemd',
    'ccripemd/src',
    'ccripemd/corecrypto',
    'cc_fips_test',
    'ccasn1',
    'ccasn1/src',
    'ccasn1/corecrypto',
    'cckprng',
    'cckprng/src',
    'cckprng/corecrypto',
    'acceleratecrypto',
    'cc',
    'cc/src',
    'cc/corecrypto',
    'ccdrbg',
    'ccdrbg/src',
    'ccdrbg/corecrypto',
    'ccansikdf',
    'ccansikdf/src',
    'ccansikdf/corecrypto',
    'ccec25519',
    'ccec25519/src',
    'ccec25519/corecrypto',
    'cccmac',
    'cccmac/src',
    'cccmac/corecrypto',
    'ccvrf',
    'ccvrf/src',
    'ccvrf/corecrypto',
    'corecrypto_l4',
    'cccast',
    'cccast/src',
    'cccast/corecrypto',
    'ccz',
    'ccz/src',
    'ccz/corecrypto',
    'ccec448',
    'ccec448/src',
    'ccec448/corecrypto',
    'cch2c',
    'cch2c/src',
    'cch2c/corecrypto',
    'ccn',
    'ccn/src',
    'ccn/src/arm',
    'ccn/corecrypto',
]
    if inc == ''
        cc_includes += ['-I' + meson.current_source_dir()]
    else
        cc_includes += ['-I' + meson.current_source_dir() / inc]
    endif
endforeach

cc_includes += [
    '-I.',
    '-I' + srcroot,
    '-I' + gen_dir,
    '-I' + srcroot / 'osfmk',
    '-I' + gen_dir / 'export' / 'osfmk',
    '-I' + srcroot / 'bsd',
    '-I' + srcroot / 'iokit',
    '-I' + srcroot / 'libkern',
    '-I' + srcroot / 'libsa',
    '-I' + srcroot / 'pexpert',
    '-I' + srcroot / 'security',
    '-I' + gen_dir / 'export',
    '-I' + srcroot / 'EXTERNAL_HEADERS',
    '-I' + buildroot / 'syscalls',
    '-I' + buildroot / 'assym',
    '-I' + mig_dir,
    '-I' + mig_ks_dir,
    '-I' + mig_dir / 'mach',
    '-I' + mig_ks_dir / 'mach',
    '-I' + mig_dir / 'device',
    '-I' + mig_ks_dir / 'device',
    '-I' + mig_dir / 'UserNotification',
    '-I' + mig_ks_dir / 'UserNotification',
    '-I' + mig_dir / 'gssd',
    '-I' + mig_ks_dir / 'gssd',
    '-I' + mig_dir / 'lockd',
    '-I' + mig_ks_dir / 'lockd',
    '-I' + mig_dir / 'kextd',
    '-I' + mig_ks_dir / 'kextd',
    '-I' + iig_dir,
]

corecrypto_flags = [
    '-target',
    target_triple,
    '-ffreestanding',
    '-fno-builtin',
    '-fno-common',
    '-fno-stack-protector',
    '-fno-strict-aliasing',
    '-fno-exceptions',
    '-momit-leaf-frame-pointer',
    '-nostdlibinc',
    '-ftrivial-auto-var-init=zero',
    '-fmerge-all-constants',
    '-Os',
    '-D' + target_arch,
    '-D' + target_arch.to_upper(),
    '-D__' + target_arch.to_upper() + '__',
    '-DLP64',
    '-DPAGE_SIZE_FIXED',
    '-UARM_LARGE_MEMORY',
    '-UARM_LARGE_MEMORY_KERNONLY',
    '-DAPPLE',
    '-DKERNEL',
    '-DKERNEL_PRIVATE',
    '-DPRIVATE',
    '-UXNU_KERNEL_PRIVATE',
    '-DXNU_PLATFORM_MacOSX',
    '-DXNU_TARGET_OS_OSX',
    '-DCC_KERNEL=1',
    '-DBUILDKERNEL=1',
    '-DCC_USE_ASM=1',
    '-DCC_DISABLE_RSAKEYGEN=1',
    '-DCORECRYPTO_SIMD=0',
    '-Wno-pointer-sign',
    '-Wno-shorten-64-to-32',
    '-Wno-unknown-warning-option',
    '-Wno-unused-command-line-argument',
    '-include',
    gen_dir / 'master_config.h',
]

corecrypto_cflags = cc_includes + corecrypto_flags + ['-std=gnu17']
corecrypto_sflags = cc_includes + corecrypto_flags + [
    '-x',
    'assembler-with-cpp',
    '-D__ASSEMBLER__',
    '-DASSEMBLER',
    '-D__apple_build_version__=21000333',
]

xnu_corecrypto_c = static_library(
    'xnu_corecrypto_c',
    c_sources,
    c_args: corecrypto_cflags,
    pic: false,
    implicit_include_directories: false,
)

xnu_corecrypto_s = static_library(
    'xnu_corecrypto_s',
    s_sources,
    c_args: corecrypto_sflags,
    pic: false,
    implicit_include_directories: false,
)

xnu_corecrypto = [xnu_corecrypto_c, xnu_corecrypto_s]
