"""Shared kernel compiler flags for all XNU build targets."""

COMMON_KERNEL_FLAGS = [
    "-I.",
    "-nostdlibinc",
    "-fno-builtin",
    "-fno-common",
    "-DAPPLE=1",
    "-DKERNEL=1",
    "-D_KERNEL=1",
    "-DKERNEL_PRIVATE=1",
    "-DXNU_KERNEL_PRIVATE=1",
    "-DMACH_KERNEL_PRIVATE=1",
    "-DMACH_BSD=1",
    "-DMACH_KDP=1",
    "-DPRIVATE=1",
    "-DXNU_TARGET_OS_OSX=1",
    "-D__MACHO__=1",
    "-fblocks",
    "-DCONFIG_SCHED_TRADITIONAL=1",
    "-DCONFIG_SCHED_MULTIQ=1",
    "-DCONFIG_SCHED_TIMESHARE_CORE=1",
    "-DCONFIG_THREAD_MAX=2560",
    "-DCONFIG_TASK_MAX=1024",
    "-DKPERF=1",
    "-DCC_INTERNAL_SDK=1",
    "-DCONFIG_MACF=1",
    "-DIMPORTANCE_INHERITANCE=1",
    "-DIMPORTANCE_DEBUG=1",
    "-DCONFIG_COALITIONS=1",
    "-DCONFIG_ATM=1",
    "-DCONFIG_TASKWATCH=1",
    "-DCONFIG_TELEMETRY=1",
    "-DCONFIG_MEMORYSTATUS=1",
    "-DCONFIG_FREEZE=1",
    "-DCONFIG_SCHED_SFI=1",
    "-DCONFIG_COREDUMP=1",
    "-DCONFIG_IO_ACCOUNTING=1",
    "-DCONFIG_DEFERRED_RECLAIM=1",
    "-DCONFIG_PHYS_WRITE_ACCT=1",
    "-DCONFIG_PROC_RESOURCE_LIMITS=1",
    "-DCONFIG_TASK_SUSPEND_STATS=1",
    "-DCONFIG_SERVICE_PORT_INFO=1",
    "-DCONFIG_ZONE_MAP_MIN=120586240",
    "-DCONFIG_MSG_BSIZE_REL=16384",
    "-DCONFIG_MSG_BSIZE_DEV=131072",
    "-DCONFIG_MSG_BSIZE=CONFIG_MSG_BSIZE_REL",
    "-DCONFIG_KDP_INTERACTIVE_DEBUGGING=1",
    "-DCONFIG_REQUIRES_U32_MUNGING=1",
    "-Wno-sign-conversion",
    "-Wno-conversion",
]

X86_64_FLAGS = [
    "-target", "x86_64-apple-darwin",
    "-Dx86_64",
    "-DX86_64",
    "-D__X86_64__",
    "-DLP64",
    "-DPAGE_SIZE_FIXED",
    "-DKERNEL_BASE_OFFSET=0x100000",
    "-mkernel",
    "-msoft-float",
]
