option(
    'kernel_config',
    type: 'combo',
    choices: ['DEVELOPMENT', 'DEBUG', 'RELEASE'],
    value: 'DEVELOPMENT',
    description: 'XNU MASTER configuration',
)
option(
    'board',
    type: 'combo',
    choices: ['qemu', 'superbird', 'ipad41'],
    value: 'qemu',
    description: 'Target board configuration',
)
option(
    'kernel_link_addr',
    type: 'string',
    value: '0xfffffff007004000',
    description: 'VM_KERNEL_LINK_ADDRESS / ld image_base',
)
option(
    'kernel_plkseg_addr',
    type: 'string',
    value: '0xfffffff004004000',
    description: '__PRELINK_TEXT segment address',
)
option(
    'kernel_linkedit_addr',
    type: 'string',
    value: '0xfffffff008004000',
    description: '__LINKEDIT segment address',
)
