bsd_c_sources = files(
    'nfs/nfs_syscalls.c',
    'nfs/nfs_gss.c',
    'nfs/nfs_serv.c',
    'nfs/nfs_socket.c',
    'nfs/nfs_srvcache.c',
    'nfs/nfs_subs.c',
    'nfs/nfs_upcall.c',
    'nfs/gss/gss_krb5_mech.c',
    'nfs/gss/ccrypto.c',
    'kern/netboot.c',
    'dev/dtrace/dtrace.c',
    'dev/dtrace/lockprof.c',
    'dev/dtrace/lockstat.c',
    'dev/dtrace/dtrace_ptss.c',
    'dev/dtrace/dtrace_subr.c',
    'dev/dtrace/dtrace_glue.c',
    'dev/dtrace/dtrace_xoroshiro128_plus.c',
    'dev/dtrace/blist.c',
    'dev/dtrace/fbt.c',
    'dev/dtrace/fbt_blacklist.c',
    'dev/dtrace/sdt.c',
    'dev/dtrace/sdt_subr.c',
    'dev/dtrace/systrace.c',
    'dev/dtrace/profile_prvd.c',
    'dev/dtrace/fasttrap.c',
    'dev/random/randomdev.c',
    'dev/memdev.c',
    'dev/mem.c',
    'dev/munge.c',
    'dev/unix_startup.c',
    'libkern/crc32.c',
    'libkern/random.c',
    'libkern/scanc.c',
    'libkern/strsep.c',
    'libkern/bcd.c',
    'libkern/memchr.c',
    'libkern/url_encode.c',
    'vfs/vfs_attrlist.c',
    'vfs/vfs_bio.c',
    'vfs/vfs_cache.c',
    'vfs/vfs_cluster.c',
    'vfs/vfs_conf.c',
    'vfs/vfs_fslog.c',
    'vfs/vfs_init.c',
    'vfs/vfs_lookup.c',
    'vfs/vfs_quota.c',
    'vfs/vfs_subr.c',
    'vfs/vfs_syscalls.c',
    'vfs/vfs_support.c',
    'vfs/vfs_utfconv.c',
    'vfs/vfs_unicode.c',
    'vfs/vfs_vnops.c',
    'vfs/vfs_xattr.c',
    'vfs/vnode_if.c',
    'vfs/kpi_vfs.c',
    'vfs/vfs_fsevents.c',
    'vfs/vfs_cprotect.c',
    'vfs/doc_tombstone.c',
    'vfs/vfs_disk_conditioner.c',
    'vfs/vfs_exclave_fs.c',
    'miscfs/deadfs/dead_vnops.c',
    'miscfs/devfs/devfs_fdesc_support.c',
    'miscfs/fifofs/fifo_vnops.c',
    'miscfs/specfs/spec_vnops.c',
    'miscfs/devfs/devfs_tree.c',
    'miscfs/devfs/devfs_vnops.c',
    'miscfs/devfs/devfs_vfsops.c',
    'miscfs/mockfs/mockfs_fsnode.c',
    'miscfs/mockfs/mockfs_vfsops.c',
    'miscfs/mockfs/mockfs_vnops.c',
    'kern/decmpfs.c',
    'net/net_stubs.c',
    'net/bpf.c',
    'net/bpf_filter.c',
    'net/if_bridge.c',
    'net/if.c',
    'net/init.c',
    'net/dlil.c',
    'net/dlil_ctl.c',
    'net/dlil_input.c',
    'net/dlil_output.c',
    'net/dlil_subr.c',
    'net/dlil_sysctl.c',
    'net/ether_if_module.c',
    'net/ether_inet_pr_module.c',
    'net/ether_inet6_pr_module.c',
    'net/if_loop.c',
    'net/if_mib.c',
    'net/if_vlan.c',
    'net/if_fake.c',
    'net/if_headless.c',
    'net/if_redirect.c',
    'net/multicast_list.c',
    'net/if_bond.c',
    'net/devtimer.c',
    'net/ndrv.c',
    'net/radix.c',
    'net/raw_cb.c',
    'net/raw_usrreq.c',
    'net/route.c',
    'net/rtsock.c',
    'net/netsrc.c',
    'net/ntstat.c',
    'net/net_perf.c',
    'net/if_gif.c',
    'net/if_stf.c',
    'net/if_ports_used.c',
    'net/if_low_power_mode.c',
    'net/kpi_interface.c',
    'net/kpi_protocol.c',
    'net/kpi_interfacefilter.c',
    'net/net_str_id.c',
    'net/if_utun.c',
    'net/if_ipsec.c',
    'net/necp.c',
    'net/necp_client.c',
    'net/network_agent.c',
    'net/bloom_filter.c',
    'net/trie_utility.c',
    'net/if_pflog.c',
    'net/nat464_utils.c',
    'net/pf.c',
    'net/pf_if.c',
    'net/pf_ioctl.c',
    'net/pf_norm.c',
    'net/pf_osfp.c',
    'net/pf_pbuf.c',
    'net/pf_ruleset.c',
    'net/pf_table.c',
    'net/iptap.c',
    'net/pktap.c',
    'net/droptap.c',
    'net/if_llreach.c',
    'net/flowhash.c',
    'net/siphash.c',
    'net/flowadv.c',
    'net/content_filter.c',
    'net/content_filter_crypto.c',
    'net/packet_mangler.c',
    'net/nwk_wq.c',
    'net/skmem_sysctl.c',
    'net/restricted_in_port.c',
    'net/remote_vif.c',
    'net/kctl_test.c',
    'net/net_thread_marks.c',
    'net/classq/classq.c',
    'net/classq/classq_subr.c',
    'net/classq/classq_util.c',
    'net/classq/classq_fq_codel.c',
    'net/pktsched/pktsched.c',
    'net/pktsched/pktsched_fq_codel.c',
    'net/pktsched/pktsched_netem.c',
    'net/pktsched/pktsched_ops.c',
    'net/aop/kpi_aop.c',
    'netinet/cpu_in_cksum_gen.c',
    'netinet/in_cksum.c',
    'netinet/igmp.c',
    'netinet/in.c',
    'netinet/dhcp_options.c',
    'netinet/in_arp.c',
    'netinet/in_mcast.c',
    'netinet/in_pcb.c',
    'netinet/in_pcblist.c',
    'netinet/in_proto.c',
    'netinet/in_rmx.c',
    'netinet/in_stat.c',
    'netinet/in_tclass.c',
    'netinet/ip_dummynet.c',
    'netinet/ip_icmp.c',
    'netinet/ip_id.c',
    'netinet/ip_input.c',
    'netinet/ip_output.c',
    'netinet/inp_log.c',
    'netinet/raw_ip.c',
    'netinet/tcp_cache.c',
    'netinet/tcp_input.c',
    'netinet/tcp_output.c',
    'netinet/tcp_sack.c',
    'netinet/tcp_subr.c',
    'netinet/tcp_timer.c',
    'netinet/tcp_usrreq.c',
    'netinet/tcp_cc.c',
    'netinet/tcp_newreno.c',
    'netinet/tcp_cubic.c',
    'netinet/tcp_prague.c',
    'netinet/tcp_pacing.c',
    'netinet/cbrtf.c',
    'netinet/tcp_ledbat.c',
    'netinet/tcp_rledbat.c',
    'netinet/tcp_rack.c',
    'netinet/tcp_syncookie.c',
    'netinet/tcp_log.c',
    'netinet/tcp_sysctls.c',
    'netinet/tcp_ccdbg.c',
    'netinet/udp_log.c',
    'netinet/udp_usrreq.c',
    'netinet/in_gif.c',
    'netinet/ip_ecn.c',
    'netinet/ip_encap.c',
    'netinet/kpi_ipfilter.c',
    'netinet/flow_divert.c',
    'netinet/mp_proto.c',
    'netinet/mp_pcb.c',
    'netinet/mptcp.c',
    'netinet/mptcp_subr.c',
    'netinet/mptcp_usrreq.c',
    'netinet/mptcp_opt.c',
    'netinet/mptcp_timer.c',
    'netinet6/ah_core.c',
    'netinet6/ah_input.c',
    'netinet6/ah_output.c',
    'netinet6/esp_core.c',
    'netinet6/esp_input.c',
    'netinet6/esp_output.c',
    'netinet6/esp_rijndael.c',
    'netinet6/esp_chachapoly.c',
    'netinet6/ipsec.c',
    'netinet6/ipsec_pwr.c',
    'netinet6/dest6.c',
    'netinet6/frag6.c',
    'netinet6/icmp6.c',
    'netinet6/in6.c',
    'netinet6/in6_cga.c',
    'netinet6/in6_cksum.c',
    'netinet6/in6_gif.c',
    'netinet6/ip6_forward.c',
    'netinet6/in6_ifattach.c',
    'netinet6/ip6_input.c',
    'netinet6/ip6_output.c',
    'netinet6/in6_src.c',
    'netinet6/in6_mcast.c',
    'netinet6/in6_pcb.c',
    'netinet6/in6_proto.c',
    'netinet6/in6_rmx.c',
    'netinet6/mld6.c',
    'netinet6/nd6.c',
    'netinet6/nd6_nbr.c',
    'netinet6/nd6_prproxy.c',
    'netinet6/nd6_rtr.c',
    'netinet6/nd6_rti.c',
    'netinet6/nd6_send.c',
    'netinet6/raw_ip6.c',
    'netinet6/route6.c',
    'netinet6/scope6.c',
    'netinet6/udp6_output.c',
    'netinet6/udp6_usrreq.c',
    'netinet6/ip6_id.c',
    'netkey/key.c',
    'netkey/key_debug.c',
    'netkey/keysock.c',
    'netkey/keydb.c',
    'net/multi_layer_pkt_log.c',
    'crypto/entropy/entropy_sysctl.c',
    'security/audit/audit.c',
    'security/audit/audit_arg.c',
    'security/audit/audit_bsd.c',
    'security/audit/audit_bsm.c',
    'security/audit/audit_bsm_errno.c',
    'security/audit/audit_bsm_fcntl.c',
    'security/audit/audit_bsm_domain.c',
    'security/audit/audit_bsm_klib.c',
    'security/audit/audit_bsm_socket_type.c',
    'security/audit/audit_bsm_token.c',
    'security/audit/audit_mac.c',
    'security/audit/audit_pipe.c',
    'security/audit/audit_session.c',
    'security/audit/audit_syscalls.c',
    'security/audit/audit_worker.c',
    'pthread/pthread_shims.c',
    'pthread/pthread_priority.c',
    'pthread/pthread_workqueue.c',
    'kern/bsd_init.c',
    'kern/kdebug_common.c',
    'kern/kdebug_triage.c',
    'kern/kdebug.c',
    'kern/kern_acct.c',
    'kern/kern_aio.c',
    'kern/kern_authorization.c',
    'kern/kern_backtrace.c',
    'kern/kern_clock.c',
    'kern/kern_core.c',
    'kern/kern_credential.c',
    'kern/kern_crossarch.c',
    'kern/kern_cs.c',
    'kern/kern_csr.c',
    'kern/kern_debug.c',
    'kern/kern_symfile.c',
    'kern/kern_descrip.c',
    'kern/kern_guarded.c',
    'kern/kern_event.c',
    'kern/kern_control.c',
    'kern/kern_exec.c',
    'kern/kern_exit.c',
    'kern/kern_ktrace.c',
    'kern/kern_lockf.c',
    'kern/kern_fork.c',
    'kern/kern_malloc.c',
    'kern/kern_persona.c',
    'kern/kern_physio.c',
    'kern/kern_priv.c',
    'kern/kern_proc.c',
    'kern/kern_prot.c',
    'kern/kern_resource.c',
    'kern/kern_shutdown.c',
    'kern/kern_sig.c',
    'kern/kern_subr.c',
    'kern/kern_synch.c',
    'kern/kern_sysctl.c',
    'kern/kern_newsysctl.c',
    'kern/kern_memorystatus.c',
    'kern/kern_memorystatus_freeze.c',
    'kern/kern_memorystatus_notify.c',
    'kern/kern_memorystatus_policy.c',
    'kern/kern_mib.c',
    'kern/kpi_mbuf.c',
    'kern/kern_sfi.c',
    'kern/kern_time.c',
    'kern/kern_trustcache.c',
    'kern/kern_codesigning.c',
    'kern/code_signing/txm.c',
    'kern/code_signing/ppl.c',
    'kern/code_signing/xnu.c',
    'kern/kern_xxx.c',
    'kern/lockdown_mode.c',
    'kern/mach_process.c',
    'kern/mem_acct.c',
    'kern/stackshot.c',
    'kern/subr_log.c',
    'kern/subr_log_stream.c',
    'kern/subr_prf.c',
    'kern/subr_sbuf.c',
    'kern/subr_xxx.c',
    'kern/counter_test.c',
    'kern/sys_ecc.c',
    'kern/sys_eventlink.c',
    'kern/sys_generic.c',
    'kern/sys_pipe.c',
    'kern/sys_record_event.c',
    'kern/sys_sched.c',
    'kern/sys_socket.c',
    'kern/sys_domain.c',
    'kern/sys_coalition.c',
    'kern/sys_persona.c',
    'kern/sys_ulock.c',
    'kern/sys_work_interval.c',
    'kern/tty.c',
    'kern/tty_compat.c',
    'kern/tty_conf.c',
    'kern/tty_dev.c',
    'kern/tty_ptmx.c',
    'kern/tty_pty.c',
    'kern/tty_subr.c',
    'kern/tty_tty.c',
    'kern/ubc_subr.c',
    'kern/uipc_domain.c',
    'kern/uipc_mbuf.c',
    'kern/uipc_mbuf2.c',
    'kern/uipc_proto.c',
    'kern/uipc_socket.c',
    'kern/uipc_socket2.c',
    'kern/uipc_syscalls.c',
    'kern/uipc_usrreq.c',
    'kern/vsock_domain.c',
    'kern/sysv_ipc.c',
    'kern/sysv_shm.c',
    'kern/sysv_sem.c',
    'kern/sysv_msg.c',
    'kern/mach_fat.c',
    'kern/mach_loader.c',
    'kern/posix_sem.c',
    'kern/posix_shm.c',
    'kern/qsort.c',
    'kern/kpi_socket.c',
    'kern/kpi_socketfilter.c',
    'kern/proc_info.c',
    'kern/process_policy.c',
    'kern/kern_overrides.c',
    'kern/socket_info.c',
    'kern/subr_eventhandler.c',
    'kern/sys_reason.c',
    'kern/sys_recount.c',
    'kern/tracker.c',
    'kern/socket_flows.c',
    'kern/hvg_sysctl.c',
    'kern/kern_ecc.c',
    'kern/kern_ntptime.c',
    'uxkern/ux_exception.c',
    'conf/param.c',
    'kern/imageboot.c',
    srcroot / 'osfmk/kperf/kperfbsd.c',
    'kern/proc_uuid_policy.c',
    'pgo/profile_runtime.c',
    'pgo/profile_runtime_data.c',
    'miscfs/nullfs/null_subr.c',
    'miscfs/nullfs/null_vfsops.c',
    'miscfs/nullfs/null_vnops.c',
    'tests/bsd_tests.c',
    'tests/copyio_tests.c',
    'tests/pmap_test_sysctl.c',
    'tests/ptrauth_data_tests_sysctl.c',
    'tests/stack_chk_tests_sysctl.c',
    'tests/readonly_proc_tests_sysctl.c',
    'tests/tree_tests_sysctl.c',
    'tests/sau_tests_sysctl.c',
    'tests/vm_parameter_validation_kern_bsd.c',
    'net/skywalk_stubs.c',
    'skywalk/namespace/netns.c',
    'skywalk/namespace/protons.c',
    'skywalk/namespace/flowidns.c',
    'skywalk/core/skywalk.c',
    'skywalk/core/skywalk_proc_info.c',
    'skywalk/core/skywalk_sysctl.c',
    'skywalk/channel/channel.c',
    'skywalk/channel/channel_kern.c',
    'skywalk/channel/channel_ring.c',
    'skywalk/channel/kern_channel_event.c',
    'skywalk/channel/channel_syscalls.c',
    'skywalk/lib/cuckoo_hashtable.c',
    'skywalk/lib/cuckoo_hashtable_test.c',
    'skywalk/lib/net_filter_event.c',
    'skywalk/mem/skmem.c',
    'skywalk/mem/skmem_arena.c',
    'skywalk/mem/skmem_cache.c',
    'skywalk/mem/skmem_region.c',
    'skywalk/mem/skmem_slab.c',
    'skywalk/mem/skmem_test.c',
    'skywalk/nexus/nexus.c',
    'skywalk/nexus/nexus_adapter.c',
    'skywalk/nexus/nexus_ioctl.c',
    'skywalk/nexus/nexus_kern.c',
    'skywalk/nexus/nexus_mbq.c',
    'skywalk/nexus/nexus_pktq.c',
    'skywalk/nexus/nexus_syscalls.c',
    'skywalk/nexus/nexus_traffic_rule.c',
    'skywalk/nexus/nexus_traffic_rule_inet.c',
    'skywalk/nexus/nexus_traffic_rule_eth.c',
    'skywalk/nexus/flowswitch/nx_flowswitch.c',
    'skywalk/nexus/flowswitch/fsw.c',
    'skywalk/nexus/flowswitch/fsw_vp.c',
    'skywalk/nexus/flowswitch/fsw_dp.c',
    'skywalk/nexus/flowswitch/fsw_ip.c',
    'skywalk/nexus/flowswitch/fsw_ip_frag.c',
    'skywalk/nexus/flowswitch/fsw_cellular.c',
    'skywalk/nexus/flowswitch/fsw_ethernet.c',
    'skywalk/nexus/flowswitch/fsw_flow.c',
    'skywalk/nexus/flowswitch/fsw_netagent.c',
    'skywalk/nexus/flowswitch/fsw_classq.c',
    'skywalk/nexus/flowswitch/fsw_qos.c',
    'skywalk/nexus/flowswitch/flow/flow.c',
    'skywalk/nexus/flowswitch/flow/flow_classifier.c',
    'skywalk/nexus/flowswitch/flow/flow_entry.c',
    'skywalk/nexus/flowswitch/flow/flow_manager.c',
    'skywalk/nexus/flowswitch/flow/flow_namespace.c',
    'skywalk/nexus/flowswitch/flow/flow_owner.c',
    'skywalk/nexus/flowswitch/flow/flow_route.c',
    'skywalk/nexus/flowswitch/flow/flow_stats.c',
    'skywalk/nexus/flowswitch/flow/flow_track.c',
    'skywalk/nexus/flowswitch/flow/flow_agg.c',
    'skywalk/nexus/netif/nx_netif.c',
    'skywalk/nexus/netif/nx_netif_compat.c',
    'skywalk/nexus/netif/nx_netif_host.c',
    'skywalk/nexus/netif/nx_netif_mit.c',
    'skywalk/nexus/netif/nx_netif_netagent.c',
    'skywalk/nexus/netif/nx_netif_filter.c',
    'skywalk/nexus/netif/nx_netif_filter_compat.c',
    'skywalk/nexus/netif/nx_netif_filter_native.c',
    'skywalk/nexus/netif/nx_netif_filter_vp.c',
    'skywalk/nexus/netif/nx_netif_flow.c',
    'skywalk/nexus/netif/nx_netif_vp.c',
    'skywalk/nexus/netif/nx_netif_util.c',
    'skywalk/nexus/netif/nx_netif_poll.c',
    'skywalk/nexus/netif/nx_netif_gso.c',
    'skywalk/nexus/netif/nx_netif_llink.c',
    'skywalk/nexus/upipe/nx_user_pipe.c',
    'skywalk/nexus/kpipe/nx_kernel_pipe.c',
    'skywalk/nexus/kpipe/nx_kpipe_loopback.c',
    'skywalk/packet/packet_copy.c',
    'skywalk/packet/packet_kern.c',
    'skywalk/packet/pbufpool.c',
    'skywalk/packet/pbufpool_kern.c',
    'dev/cpu_copy_in_cksum_gen.c',
    'dev/arm64/conf.c',
    'dev/arm/cons.c',
    'dev/arm/km.c',
    'dev/arm/kern_machdep.c',
    'dev/arm/stubs.c',
    'dev/arm/systemcalls.c',
    'dev/arm64/sysctl.c',
    'dev/arm/unix_signal.c',
    'dev/arm64/dtrace_isa.c',
    'dev/arm64/dtrace_subr_arm.c',
    'dev/arm64/fbt_arm.c',
    'dev/arm64/fasttrap_isa.c',
    'dev/arm64/disassembler.c',
    'dev/arm64/sdt_arm.c',
    'kern/bsd_stubs.c',
)
bsd_vm_sources = files(
    'vm/vnode_pager.c',
    'vm/vm_unix.c',
    'vm/dp_backing_file.c',
    'vm/vm_compressor_backing_file.c',
)
bsd_mman_sources = files(
    'kern/kern_mman.c',
)
bsd_cpp_sources = files(
    'vfs/vfs_exclave_fs_helper.cpp',
)
bsd_s_sources = files(
    'dev/arm64/cpu_in_cksum.s',
    'dev/arm64/cpu_copy_in_cksum.s',
    'dev/arm64/cpu_memcmp_mask.s',
)

bsd_cflags = comp_cflags['bsd'] + c_args
bsd_cxxflags = comp_cflags['bsd'] + cxx_args
bsd_sflags = comp_cflags['bsd'] + s_args

xnu_bsd = static_library(
    'xnu_bsd',
    bsd_c_sources + bsd_cpp_sources + [
        syscalls_gen[0],
        syscalls_gen[1],
        syscalls_gen[2],
        syscalls_gen[3],
        ioconf_c,
    ] + gen_order,
    c_args: bsd_cflags,
    cpp_args: bsd_cxxflags,
    kwargs: lib_kwargs,
)

xnu_bsd_vm = static_library(
    'xnu_bsd_vm',
    bsd_vm_sources + gen_order,
    c_args: bsd_cflags + ['-DVM_UNSAFE_TYPES'],
    kwargs: lib_kwargs,
)

xnu_bsd_mman = static_library(
    'xnu_bsd_mman',
    bsd_mman_sources + gen_order,
    c_args: bsd_cflags + ['-DVM_UNSAFE_TYPES'],
    kwargs: lib_kwargs,
)

xnu_bsd_asm = static_library(
    'xnu_bsd_asm',
    bsd_s_sources + gen_order,
    c_args: bsd_sflags,
    kwargs: lib_kwargs,
)

kernel_libs += [xnu_bsd, xnu_bsd_vm, xnu_bsd_mman, xnu_bsd_asm]
