load("@rules_cc//cc:defs.bzl", "cc_library")
load("//bazel:rules.bzl", "genassym")
load("//bazel:mig.bzl", "mig_library")

package(default_visibility = ["//visibility:public"])

# Common kernel flags from root
COMMON_KERNEL_FLAGS = [
    "-I./",
    "-nostdlibinc",
    "-fno-builtin",
    "-fno-common",
    "-DAPPLE=1",
    "-DKERNEL=1",
    "-D_KERNEL=1",
    "-DKERNEL_SERVER=1",
    "-DKERNEL_PRIVATE=1",
    "-DXNU_KERNEL_PRIVATE=1",
    "-DMACH_KERNEL_PRIVATE=1",
    "-DMACH_BSD=1",
    "-DMACH_KDP=1",
    "-DPRIVATE=1",
    "-DXNU_TARGET_OS_OSX=1",
    "-D__MACHO__=1",
    "-fblocks",
    "-DCONFIG_SCHED_TRADITIONAL=1",
    "-DCONFIG_SCHED_MULTIQ=1",
    "-DCONFIG_SCHED_CLUTCH=1",
    "-DCONFIG_SCHED_TIMESHARE_CORE=1",
    "-DCONFIG_THREAD_MAX=2560",
    "-DCONFIG_TASK_MAX=1024",
    "-DKPERF=1",
    "-DCONFIG_SLEEP=1",
    "-DCONFIG_DTRACE=1",
    "-DHIBERNATION=1",
    "-DCC_INTERNAL_SDK=1",
]

X86_64_FLAGS = [
    "-target", "x86_64-apple-darwin",
    "-Dx86_64",
    "-DX86_64",
    "-D__X86_64__",
    "-DLP64",
    "-DPAGE_SIZE_FIXED",
    "-DKERNEL_BASE_OFFSET=0x100000",
    "-mkernel",
    "-msoft-float",
]

BOOT_INCLUDE_FLAGS = [
    "-Iosfmk",
    "-Iosfmk/console",
    "-Iosfmk/i386",
    "-Iosfmk/x86_64",
    "-Iosfmk/kern",
    "-Iosfmk/mach",
    "-Iosfmk/libsa",
    "-Ibsd",
    "-Ipexpert",
    "-IEXTERNAL_HEADERS",
    "-Ibuild_config",
    "-Iiokit",
    "-Ilibkern",
    "-Ibazel-out/k8-fastbuild/bin/osfmk",
]

filegroup(
    name = "osfmk_headers",
    srcs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "system_mach_headers",
    hdrs = glob(["mach/**/*.h"]),
    include_prefix = "System/mach",
    strip_include_prefix = "mach",
    visibility = ["//visibility:public"],
)

genassym(
    name = "assym_s",
    src = "i386/genassym.c",
    out = "assym.s",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    hdrs = ["//:all_headers", "//:config_header_files"],
    includes = [
        "build_config",
        "osfmk",
        "bsd",
        "osfmk/libsa",
        "osfmk/kern",
        "osfmk/mach",
        "osfmk/i386",
        "osfmk/x86_64",
        "libkern",
        "EXTERNAL_HEADERS",
        "pexpert",
        "iokit",
    ],
    deps = ["//:common_headers"],
)

genrule(
    name = "debug_sandbox",
    srcs = ["//:all_headers"],
    outs = ["sandbox_listing.txt"],
    cmd = "find . -maxdepth 5 > $@",
)

genrule(
    name = "start_S",
    srcs = ["x86_64/start.s"],
    outs = ["x86_64/start.S"],
    cmd = "cp $< $@",
)

cc_library(
    name = "osfmk_start",
    srcs = [
        "x86_64/start.S",
        "x86_64/machine_routines_asm.s",
    ],
    hdrs = [":assym_s"],
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS + BOOT_INCLUDE_FLAGS + ["-DASSEMBLER"],
    includes = [".", "console"],
    deps = ["//:common_headers", ":osfmk_start_c"],
    linkstatic = True,
)

cc_library(
    name = "osfmk_test_task",
    srcs = [
        "kern/affinity.c",
        "kern/ast.c",
        "kern/backtrace.c",
        "kern/btlog.c",
        "kern/build_config.c",
        "kern/compact_id.c",
        "kern/counter_common.c",
        "kern/host.c",
        "kern/host_notify.c",
    ],
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS + BOOT_INCLUDE_FLAGS,
    deps = [
        "//:common_headers",
        "//:config_headers",
        ":host_notify_reply_mig",
        ":mach_test_upcall_mig",
    ],
    linkstatic = True,
)

cc_library(
    name = "osfmk_start_c",
    srcs = [
        "console/serial_console.c",
        "console/serial_general.c",
        "console/video_console.c",
        "x86_64/bcopy.s",
        "i386/AT386/model_dep.c",
        "i386/Diagnostics.c",
        "i386/acpi.c",
        "i386/cpu.c",
        "i386/cpu_threads.c",
        "i386/cpuid.c",
        "i386/fp_simd.s",
        "i386/fpu.c",
        "i386/locks_i386.c",
        "x86_64/boot_pt.c",
        "i386/gdt.c",
        "i386/i386_init.c",
        "i386/i386_vm_init.c",
        "i386/hibernate_restore.c",
        "i386/lapic.c",
        "i386/lapic_native.c",
        "i386/machine_routines.c",
        "i386/mp.c",
        "i386/mp_desc.c",
        "i386/pal_routines.c",
        "i386/pcb.c",
        "i386/pcb_native.c",
        "i386/panic_hooks.c",
        "i386/panic_notify.c",
        "i386/pmap_x86_common.c",
        "i386/pmCPU.c",
        "i386/rtclock.c",
        "i386/tsc.c",
        "i386/ucode.c",
        "kern/bsd_kern.c",
        "kern/clock.c",
        "kern/debug.c",
        "kern/kern_cdata.c",
        "kern/kern_stackshot.c",
        "kern/locks.c",
        "kern/machine.c",
        "kern/processor.c",
        "kern/printf.c",
        "kern/sched_prim.c",
        "kern/startup.c",
        "kern/task.c",
        "kern/thread.c",
        "kern/timer_call.c",
        "kern/zalloc.c",
        "kdp/kdp_core.c",
        "prng/prng_random.c",
        "x86_64/copyio.c",
        "x86_64/loose_ends.c",
        "x86_64/pmap.c",
        "//:libkern/stack_protector.c",
        "//:libkern/gen/OSAtomicOperations.c",
    ],
    textual_hdrs = [
        "console/iso_font.c",
        "console/progress_meter_data.c",
    ],
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS + BOOT_INCLUDE_FLAGS,
    includes = [".", "console"],
    deps = ["//:common_headers", "//:config_headers", "//:crc32_support", "//:early_string_support", "//:early_vm_support", "//:kernel_version_support", "//:pexpert_kprintf_support"],
    linkstatic = True,
)

filegroup(
    name = "common_mig_defs",
    srcs = glob([
        "mach/**/*.defs",
        "mach_debug/**/*.defs",
        "mach/**/*.h",
    ]) + ["//:external_headers_filegroup"],
    visibility = ["//visibility:public"],
)

mig_library(
    name = "clock_mig",
    src = "mach/clock.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/clock_server.c",
    server_h = "mach/clock_server.h",
    user_c = "mach/clock_user.c",
    user_h = "mach/clock.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "clock_priv_mig",
    src = "mach/clock_priv.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/clock_priv_server.c",
    server_h = "mach/clock_priv_server.h",
    user_c = "mach/clock_priv_user.c",
    user_h = "mach/clock_priv.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "clock_reply_mig",
    src = "mach/clock_reply.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/clock_reply_server.c",
    server_h = "mach/clock_reply_server.h",
    user_c = "mach/clock_reply_user.c",
    user_h = "mach/clock_reply.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "host_priv_mig",
    src = "mach/host_priv.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/host_priv_server.c",
    server_h = "mach/host_priv_server.h",
    user_c = "mach/host_priv_user.c",
    user_h = "mach/host_priv.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "host_security_mig",
    src = "mach/host_security.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/host_security_server.c",
    server_h = "mach/host_security_server.h",
    user_c = "mach/host_security_user.c",
    user_h = "mach/host_security.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "mach_host_mig",
    src = "mach/mach_host.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/mach_host_server.c",
    server_h = "mach/mach_host_server.h",
    user_c = "mach/mach_host_user.c",
    user_h = "mach/mach_host.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "mach_port_mig",
    src = "mach/mach_port.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/mach_port_server.c",
    server_h = "mach/mach_port_server.h",
    user_c = "mach/mach_port_user.c",
    user_h = "mach/mach_port.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "processor_mig",
    src = "mach/processor.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/processor_server.c",
    server_h = "mach/processor_server.h",
    user_c = "mach/processor_user.c",
    user_h = "mach/processor.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "processor_set_mig",
    src = "mach/processor_set.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/processor_set_server.c",
    server_h = "mach/processor_set_server.h",
    user_c = "mach/processor_set_user.c",
    user_h = "mach/processor_set.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "task_mig",
    src = "mach/task.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/task_server.c",
    server_h = "mach/task_server.h",
    user_c = "mach/task_user.c",
    user_h = "mach/task.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "thread_act_mig",
    src = "mach/thread_act.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/thread_act_server.c",
    server_h = "mach/thread_act_server.h",
    user_c = "mach/thread_act_user.c",
    user_h = "mach/thread_act.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "resource_notify_mig",
    src = "mach/resource_notify.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/resource_notify_server.c",
    server_h = "mach/resource_notify_server.h",
    user_c = "mach/resource_notify_user.c",
    user_h = "mach/resource_notify.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "mach_vm_mig",
    src = "mach/mach_vm.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/mach_vm_server.c",
    server_h = "mach/mach_vm_server.h",
    user_c = "mach/mach_vm_user.c",
    user_h = "mach/mach_vm.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "mach_voucher_mig",
    src = "mach/mach_voucher.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/mach_voucher_server.c",
    server_h = "mach/mach_voucher_server.h",
    user_c = "mach/mach_voucher_user.c",
    user_h = "mach/mach_voucher.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "vm_map_mig",
    src = "mach/vm_map.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/vm_map_server.c",
    server_h = "mach/vm_map_server.h",
    user_c = "mach/vm_map_user.c",
    user_h = "mach/vm_map.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "exc_mig",
    src = "mach/exc.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/exc_server.c",
    server_h = "mach/exc_server.h",
    user_c = "mach/exc_user.c",
    user_h = "mach/exc.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "mach_eventlink_mig",
    src = "mach/mach_eventlink.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/mach_eventlink_server.c",
    server_h = "mach/mach_eventlink_server.h",
    user_c = "mach/mach_eventlink_user.c",
    user_h = "mach/mach_eventlink.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "ktrace_background_mig",
    src = "mach/ktrace_background.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/ktrace_background_server.c",
    server_h = "mach/ktrace_background_server.h",
    user_c = "mach/ktrace_background_user.c",
    user_h = "mach/ktrace_background.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "mach_exc_mig",
    src = "mach/mach_exc.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/mach_exc_server.c",
    server_h = "mach/mach_exc_server.h",
    user_c = "mach/mach_exc_user.c",
    user_h = "mach/mach_exc.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "mach_notify_mig",
    src = "mach/mach_notify.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/mach_notify_server.c",
    server_h = "mach/mach_notify_server.h",
    user_c = "mach/mach_notify_user.c",
    user_h = "mach/mach_notify.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "memory_entry_mig",
    src = "mach/memory_entry.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/memory_entry_server.c",
    server_h = "mach/memory_entry_server.h",
    user_c = "mach/memory_entry_user.c",
    user_h = "mach/memory_entry.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "restartable_mig",
    src = "mach/restartable.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/restartable_server.c",
    server_h = "mach/restartable_server.h",
    user_c = "mach/restartable_user.c",
    user_h = "mach/restartable.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "audit_triggers_mig",
    src = "mach/audit_triggers.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/audit_triggers_server.c",
    server_h = "mach/audit_triggers_server.h",
    user_c = "mach/audit_triggers_user.c",
    user_h = "mach/audit_triggers.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "task_access_mig",
    src = "mach/task_access.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/task_access_server.c",
    server_h = "mach/task_access_server.h",
    user_c = "mach/task_access_user.c",
    user_h = "mach/task_access.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "vm32_map_mig",
    src = "mach/vm32_map.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/vm32_map_server.c",
    server_h = "mach/vm32_map_server.h",
    user_c = "mach/vm32_map_user.c",
    user_h = "mach/vm32_map.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "mach_test_upcall_mig",
    src = "mach/mach_test_upcall.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/mach_test_upcall_server.c",
    server_h = "mach/mach_test_upcall_server.h",
    user_c = "mach/mach_test_upcall_user.c",
    user_h = "mach/mach_test_upcall.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "vfs_nspace_mig",
    src = "mach/vfs_nspace.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/vfs_nspace_server.c",
    server_h = "mach/vfs_nspace_server.h",
    user_c = "mach/vfs_nspace_user.c",
    user_h = "mach/vfs_nspace.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "host_notify_reply_mig",
    src = "mach/host_notify_reply.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/host_notify_reply_server.c",
    server_h = "mach/host_notify_reply_server.h",
    user_c = "mach/host_notify_reply_user.c",
    user_h = "mach/host_notify_reply.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

mig_library(
    name = "doubleagent_mig",
    src = "mach/doubleagent_mig.defs",
    deps = [":common_mig_defs"],
    cpp_flags = ["-D__MACH30__"] + COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    mig_flags = ["-kernel", "-mach_msg2", "-novouchers"],
    server_c = "mach/doubleagent_mig_server.c",
    server_h = "mach/doubleagent_mig_server.h",
    user_c = "mach/doubleagent_mig_user.c",
    user_h = "mach/doubleagent_mig.h",
    copts = COMMON_KERNEL_FLAGS + X86_64_FLAGS,
    visibility = ["//visibility:public"],
)

ALL_MIG_GENS = [
    ":clock_mig_gen",
    ":clock_priv_mig_gen",
    ":clock_reply_mig_gen",
    ":host_priv_mig_gen",
    ":host_security_mig_gen",
    ":mach_host_mig_gen",
    ":mach_port_mig_gen",
    ":mach_vm_mig_gen",
    ":mach_voucher_mig_gen",
    ":processor_mig_gen",
    ":processor_set_mig_gen",
    ":resource_notify_mig_gen",
    ":task_mig_gen",
    ":thread_act_mig_gen",
    ":vm_map_mig_gen",
    ":exc_mig_gen",
    ":mach_eventlink_mig_gen",
    ":ktrace_background_mig_gen",
    ":mach_exc_mig_gen",
    ":mach_notify_mig_gen",
    ":memory_entry_mig_gen",
    ":restartable_mig_gen",
    ":audit_triggers_mig_gen",
    ":task_access_mig_gen",
    ":vm32_map_mig_gen",
    ":mach_test_upcall_mig_gen",
    ":vfs_nspace_mig_gen",
    ":doubleagent_mig_gen",
]

filegroup(
    name = "clock_headers_files",
    srcs = ALL_MIG_GENS,
    output_group = "hdrs",
)

cc_library(
    name = "clock_headers",
    hdrs = ALL_MIG_GENS,
    includes = ["."],
    visibility = ["//visibility:public"],
)
