osfmk_c_sources = files(
    'UserNotification/KUNCUserNotifications.c',
    'kdp/kdp.c',
    'kern/kern_stackshot.c',
    'kern/testpoints.c',
    'kern/exclaves_test_stackshot.c',
    'kdp/kdp_common.c',
    'kdp/kdp_udp.c',
    'kdp/kdp_core.c',
    'kdp/user_core.c',
    'kdp/output_stages/out_aea.c',
    'kdp/output_stages/out_buffer.c',
    'kdp/output_stages/out_disk.c',
    'kdp/output_stages/out_lz4.c',
    'kdp/output_stages/out_net.c',
    'kdp/output_stages/out_progress_notify.c',
    'kdp/output_stages/out_shmem.c',
    'kdp/output_stages/out_zlib.c',
    'kdp/output_stages/out_memory_backing_aware_buffer.c',
    'kdp/processor_core.c',
    'kdp/kdp_serial.c',
    'ipc/ipc_entry.c',
    'ipc/ipc_eventlink.c',
    'ipc/ipc_hash.c',
    'ipc/ipc_importance.c',
    'ipc/ipc_init.c',
    'ipc/ipc_kmsg.c',
    'ipc/ipc_mqueue.c',
    'ipc/ipc_notify.c',
    'ipc/ipc_object.c',
    'ipc/ipc_policy.c',
    'ipc/ipc_port.c',
    'ipc/ipc_pset.c',
    'ipc/ipc_right.c',
    'ipc/ipc_space.c',
    'ipc/ipc_service_port.c',
    'ipc/ipc_voucher.c',
    'ipc/mach_debug.c',
    'ipc/mach_kernelrpc.c',
    'ipc/mach_msg.c',
    'ipc/mach_port.c',
    'kern/affinity.c',
    'kern/arcade.c',
    'kern/ast.c',
    'kern/audit_sessionport.c',
    'kern/backtrace.c',
    'kern/btlog.c',
    'kern/build_config.c',
    'kern/clock.c',
    'kern/clock_oldops.c',
    'kern/coalition.c',
    'kern/compact_id.c',
    'kern/core_analytics.c',
    'kern/counter_common.c',
    'kern/debug.c',
    'kern/ext_paniclog.c',
    'kern/energy_perf.c',
    'kern/exception.c',
    'kern/exception_policy.c',
    'kern/exclaves.c',
    'kern/exclaves_aoe.c',
    'kern/exclaves_boot.c',
    'kern/exclaves_conclave.c',
    'kern/exclaves_driverkit.c',
    'kern/exclaves_frame_mint.c',
    'kern/exclaves_inspection.c',
    'kern/exclaves_log.c',
    'kern/exclaves_memory.c',
    'kern/exclaves_panic.c',
    'kern/exclaves_resource.c',
    'kern/exclaves_sensor.c',
    'kern/exclaves_shared_memory.c',
    'kern/exclaves_storage.c',
    'kern/exclaves_tests.c',
    'kern/exclaves_upcalls.c',
    'kern/exclaves_xnuproxy.c',
    'kern/extmod_statistics.c',
    'kern/host.c',
    'kern/host_notify.c',
    'kern/ipc_clock.c',
    'kern/ipc_host.c',
    'kern/ipc_kobject.c',
    'kern/ipc_mig.c',
    'kern/ipc_misc.c',
    'kern/ipc_tt.c',
    'kern/kalloc.c',
    'kern/cxx_runtime_stub.c',
    'kern/kern_apfs_reflock.c',
    'kern/ktrace_background_notify.c',
    'kern/ledger.c',
    'kern/lock_group.c',
    'kern/lock_mtx.c',
    'kern/lock_ptr.c',
    'kern/lock_rw_old.c',
    'kern/lock_rw.c',
    'kern/lock_ticket.c',
    'kern/locks.c',
    'kern/machine.c',
    'kern/mk_sp.c',
    'kern/mk_timer.c',
    'kern/mpsc_ring.c',
    'kern/mpsc_queue.c',
    'kern/page_decrypt.c',
    'kern/printf.c',
    'kern/priority.c',
    'kern/processor.c',
    'kern/recount.c',
    'kern/restartable.c',
    'kern/sched_average.c',
    'kern/sched_clutch.c',
    'kern/sched_common.c',
    'kern/sched_dualq.c',
    'kern/sched_prim.c',
    'kern/sched_rt.c',
    'kern/sfi.c',
    'kern/smr.c',
    'kern/stack.c',
    'kern/startup.c',
    'kern/static_if_common.c',
    'kern/sync_sema.c',
    'kern/syscall_subr.c',
    'kern/syscall_sw.c',
    'kern/sysdiagnose.c',
    'kern/task.c',
    'kern/task_policy.c',
    'kern/task_ref.c',
    'kern/test_lock.c',
    'kern/test_mpsc_queue.c',
    'kern/thread.c',
    'kern/thread_act.c',
    'kern/thread_call.c',
    'kern/thread_group.c',
    'kern/thread_policy.c',
    'kern/thread_test_context.c',
    'kern/timeout.c',
    'kern/timer.c',
    'kern/timer_call.c',
    'kern/turnstile.c',
    'kern/ux_handler.c',
    'kern/waitq.c',
    'kern/work_interval.c',
    'kern/workload_config.c',
    'kern/zalloc.c',
    'kern/zalloc_bounds.c',
    'kern/bsd_kern.c',
    'kern/remote_time.c',
    'kern/memset_s.c',
    'kern/task_ident.c',
    'kern/socd_client.c',
    'kern/iotrace.c',
    'corpses/corpse.c',
    'kern/kern_cdata.c',
    'tests/kernel_tests.c',
    'tests/ktest.c',
    'tests/ktest_accessor.c',
    'tests/ktest_emit.c',
    'tests/ktest_global.c',
    'tests/pmap_tests.c',
    'tests/ptrauth_data_tests.c',
    'tests/bitmap_test.c',
    'tests/test_thread_call.c',
    'tests/vfp_state_test.c',
    'tests/vm_parameter_validation_kern.c',
    'tests/bcopy_test.c',
    'bank/bank.c',
    'atm/atm.c',
    'voucher/ipc_pthread_priority.c',
    'device/iokit_rpc.c',
    'device/device_init.c',
    'kern/kext_alloc.c',
    'kern/kmod.c',
    'device/subrs.c',
    'kperf/kperf.c',
    'kperf/action.c',
    'kperf/callstack.c',
    'kperf/pet.c',
    'kperf/thread_samplers.c',
    'kperf/task_samplers.c',
    'kperf/meminfo.c',
    'kperf/kptimer.c',
    'kperf/kdebug_trigger.c',
    'kperf/lazy.c',
    'kern/kpc_common.c',
    'console/serial_general.c',
    'console/serial_console.c',
    'console/video_scroll.c',
    'console/video_console.c',
    'kern/telemetry.c',
    'kern/trap_telemetry.c',
    'kern/bootprofile.c',
    'prng/prng_random.c',
    'prng/entropy.c',
    'arm/pmap/pmap.c',
    'arm/pmap/pmap_cs.c',
    'arm/pmap/pmap_data.c',
    'arm/pmap/pmap_iommu.c',
    'arm/pmap/pmap_misc.c',
    'arm/pmap/pmap_ppl_interface.c',
    'arm64/ppl/sart.c',
    'arm64/bsd_arm64.c',
    'arm/machdep_call.c',
    'arm64/amcc_rorgn_ppl.c',
    'arm64/amcc_rorgn_ppl_amcc.c',
    'arm64/amcc_rorgn_common.c',
    'arm64/amcc_rorgn_pv_ctrr.c',
    'arm/caches.c',
    'arm64/copyio.c',
    'arm64/cpu.c',
    'arm/cpu_common.c',
    'arm/cpuid.c',
    'arm64/dbgwrap.c',
    'arm/arm_timer.c',
    'arm/arm_init.c',
    'arm64/arm_vm_init.c',
    'arm64/arm64_hypercall.c',
    'arm/io_map.c',
    'arm64/loose_ends.c',
    'arm/locks_arm.c',
    'arm64/iofilter.c',
    'arm64/lowmem_vectors.c',
    'arm64/sleh.c',
    'arm/machine_cpuid.c',
    'arm/machine_routines_common.c',
    'arm64/machine_routines.c',
    'arm64/machine_task.c',
    'arm/machine_routines_apple.c',
    'arm/pal_routines.c',
    'arm/preemption_disable.c',
    'arm/model_dep.c',
    'arm64/pcb.c',
    'arm/rtclock.c',
    'arm64/status.c',
    'arm/status_shared.c',
    'arm/commpage/commpage.c',
    'kdp/ml/arm/kdp_machdep.c',
    'kdp/ml/arm/kdp_vm.c',
    'arm64/platform_tests.c',
    'arm64/alternate_debugger.c',
    'arm64/machine_remote_time.c',
    'arm64/mte.c',
    'arm64/vm_mte_compress.c',
    'arm64/sme.c',
    'arm64/static_if.c',
    'arm64/x86_64_compat.c',
    'arm/counter.c',
    'kern/ecc_init.c',
    'kern/ecc_logging.c',
    'kern/memory_error_logging.c',
)
osfmk_vm_sources = files(
    'vm/analytics.c',
    'vm/vm_sanitize_telemetry.c',
    'vm/bsd_vm.c',
    'vm/vm_compressor.c',
    'vm/vm_compressor_pager.c',
    'vm/vm_compressor_backing_store.c',
    'vm/vm_compressor_algorithms.c',
    'vm/lz4.c',
    'vm/device_vm.c',
    'vm/memory_object.c',
    'vm/vm_debug.c',
    'vm/vm_fault.c',
    'vm/vm_init.c',
    'vm/vm_kern.c',
    'vm/vm_map.c',
    'vm/vm_map_store.c',
    'vm/vm_memory_entry.c',
    'vm/vm_memtag.c',
    'vm/vm_object.c',
    'vm/vm_pageout.c',
    'vm/vm_pmap.c',
    'vm/vm_purgeable.c',
    'vm/vm_reclaim.c',
    'vm/vm_resident.c',
    'vm/vm_mteinfo.c',
    'vm/vm_mte_tests.c',
    'vm/vm_shared_region.c',
    'vm/vm_shared_region_pager.c',
    'vm/vm_dyld_pager.c',
    'vm/vm_swapfile_pager.c',
    'vm/vm_tests.c',
    'vm/vm_upl.c',
    'vm/vm_user.c',
    'vm/vm32_user.c',
    'vm/vm_sanitize.c',
    'vm/vm_sanitize_error_compat.c',
    'vm/vm_entry_lock.c',
    'vm/vm_stackshot_utils.c',
    'vm/vm_map_lock.c',
    'vm/vm_test_utils.c',
    'vm/vm_apple_protect.c',
)
osfmk_s_sources = files(
    'arm64/WKdmDecompress_16k.s',
    'arm64/WKdmCompress_16k.s',
    'arm64/WKdmDecompress_4k.s',
    'arm64/WKdmCompress_4k.s',
    'arm64/WKdmData.s',
    'arm64/lz4_decode_arm64.s',
    'arm64/lz4_encode_arm64.s',
    'arm64/bcopy.s',
    'arm64/bzero.s',
    'arm64/caches_asm.s',
    'arm/data.s',
    'arm64/locore.s',
    'arm64/iofilter_asm.s',
    'arm64/gxf_exceptions.s',
    'arm64/start.s',
    'arm64/pinst.s',
    'arm64/cswitch.s',
    'arm64/machine_routines_asm.s',
    'arm64/memcmp_zero.s',
    'arm64/strnlen.s',
    'arm64/strncmp.s',
    'arm/commpage/commpage_asm.s',
    'arm64/platform_tests_asm.s',
    'arm64/alternate_debugger_asm.s',
)

osfmk_cflags = mig_ks_incs + c_args + comp_cflags['osfmk'] + [
    '-Wno-implicit-function-declaration',
    '-Wno-int-conversion',
]
osfmk_vm_cflags = mig_ks_incs + c_args + comp_cflags['osfmk'] + [
    '-DVM_UNSAFE_TYPES',
]
osfmk_sflags = mig_ks_incs + s_args + comp_cflags['osfmk']

xnu_osfmk = static_library(
    'xnu_osfmk',
    osfmk_c_sources + mig_c + [version_c] + gen_order,
    c_args: osfmk_cflags,
    kwargs: lib_kwargs,
)

xnu_osfmk_vm = static_library(
    'xnu_osfmk_vm',
    osfmk_vm_sources + gen_order,
    c_args: osfmk_vm_cflags,
    kwargs: lib_kwargs,
)

xnu_osfmk_asm = static_library(
    'xnu_osfmk_asm',
    osfmk_s_sources + gen_order,
    c_args: osfmk_sflags,
    kwargs: lib_kwargs,
)

kernel_libs += [xnu_osfmk, xnu_osfmk_vm, xnu_osfmk_asm]
