libkern_c_sources = files(
    'gen/OSAtomicOperations.c',
    'gen/OSSpinLock.c',
    'c++/OSRuntimeSupport.c',
    'mkext.c',
    'OSKextVersion.c',
    'net/inet_aton.c',
    'net/inet_ntoa.c',
    'net/inet_ntop.c',
    'net/inet_pton.c',
    'stdio/scanf.c',
    'uuid/uuid.c',
    'os/log.c',
    'os/log_encode.c',
    'os/log_mem.c',
    'os/log_queue.c',
    'os/object.c',
    'os/internal.c',
    'os/refcnt.c',
    'os/system_event_log.c',
    'kernel_mach_header.c',
    'zlib/adler32.c',
    'zlib/compress.c',
    'zlib/z_crc32.c',
    'zlib/deflate.c',
    'zlib/infback.c',
    'zlib/inffast.c',
    'zlib/inflate.c',
    'zlib/inftrees.c',
    'zlib/trees.c',
    'zlib/uncompr.c',
    'zlib/zutil.c',
    'crypto/register_crypto.c',
    'crypto/corecrypto_sha2.c',
    'crypto/corecrypto_sha1.c',
    'crypto/corecrypto_md5.c',
    'crypto/corecrypto_des.c',
    'crypto/corecrypto_aes.c',
    'crypto/corecrypto_aesxts.c',
    'crypto/corecrypto_rand.c',
    'crypto/corecrypto_rsa.c',
    'crypto/corecrypto_chacha20poly1305.c',
    'coretrust/coretrust.c',
    'apple_encrypted_archive/apple_encrypted_archive.c',
    'img4/interface.c',
    'image4/dlxk.c',
    'amfi/amfi.c',
    'stack_protector.c',
    'ptrauth_utils.c',
    'libclosure/libclosuredata.c',
    'compression/compression.c',
    'crypto/kmod_corecrypto.c',
)
libkern_cpp_sources = files(
    'gen/OSDebug.cpp',
    'c++/OSMetaClass.cpp',
    'c++/OSObject.cpp',
    'c++/OSArray.cpp',
    'c++/OSBoolean.cpp',
    'c++/OSCollection.cpp',
    'c++/OSCollectionIterator.cpp',
    'c++/OSData.cpp',
    'c++/OSDictionary.cpp',
    'c++/OSIterator.cpp',
    'c++/OSKext.cpp',
    'c++/OSNumber.cpp',
    'c++/OSOrderedSet.cpp',
    'c++/OSRuntime.cpp',
    'c++/OSSerialize.cpp',
    'c++/OSSet.cpp',
    'c++/OSString.cpp',
    'c++/OSSymbol.cpp',
    'c++/OSUnserialize.cpp',
    'c++/OSUnserializeXML.cpp',
    'c++/OSSerializeBinary.cpp',
    'c++/OSValueObject.cpp',
    'c++/priority_queue.cpp',
    'coreanalytics/coreanalytics_shim.cpp',
    'OSKextLib.cpp',
    'libclosure/runtime.cpp',
)

cc_dir = srcroot / 'subprojects/corecrypto'
libkern_cflags = comp_cflags['libkern'] + c_args + [
    '-I' + cc_dir / 'cc_fips',
    '-I' + cc_dir / 'ccdigest',
    '-I' + cc_dir / 'ccsha2',
    '-I' + cc_dir / 'corecrypto_static',
    '-I' + cc_dir / 'cc',
    '-I' + cc_dir / 'config',
]
libkern_cxxflags = comp_cflags['libkern'] + cxx_args

xnu_libkern = static_library(
    'xnu_libkern',
    libkern_c_sources + libkern_cpp_sources + gen_order,
    c_args: libkern_cflags,
    cpp_args: libkern_cxxflags,
    kwargs: lib_kwargs,
)

kernel_libs += [xnu_libkern]
