/*
 * Builtin IOKit personalities for in-kernel drivers. One XML array, one
 * C string: KLDBootstrap::readBuiltinPersonalities() unserializes
 * __TEXT,__builtin_info as a single C string, so a second NUL-terminated
 * blob in the same section is never parsed.
 *
 * This lives in __TEXT (a standard, always-mapped segment covered by
 * arm_vm_init.c's normal __TEXT_EXEC/__TEXT mapping) rather than a
 * bespoke __BUILTIN segment: pmap bootstrap on arm64 maps kernel image
 * segments by an explicit, hardcoded allowlist (__TEXT, __DATA_CONST,
 * __TEXT_EXEC, __KLD, __LAST, __KLDDATA, __DATA, __BOOTDATA,
 * __LINKEDIT, ...); an unrecognized custom segment name is simply never
 * mapped, so the first real read of its contents takes a data abort.
 * A custom *section* inside an already-mapped, already-known segment
 * has no such problem and needs no pmap changes at all.
 */

__attribute__((used, section("__TEXT,__builtin_info")))
const char gIOPL031RTCBuiltinInfo[] =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
"<plist version=\"1.0\">\n"
"<array>\n"
"\t<dict>\n"
"\t\t<key>IOKitPersonalities</key>\n"
"\t\t<dict>\n"
"\t\t\t<key>IOPL031RTC</key>\n"
"\t\t\t<dict>\n"
"\t\t\t\t<key>IOClass</key>\n"
"\t\t\t\t<string>IOPL031RTC</string>\n"
"\t\t\t\t<key>IOProviderClass</key>\n"
"\t\t\t\t<string>IOResources</string>\n"
"\t\t\t\t<key>IOMatchCategory</key>\n"
"\t\t\t\t<string>IOPL031RTC</string>\n"
"\t\t\t\t<key>IOProbeScore</key>\n"
"\t\t\t\t<integer>1000</integer>\n"
"\t\t\t</dict>\n"
"\t\t</dict>\n"
"\t</dict>\n"
"\t<dict>\n"
"\t\t<key>IOKitPersonalities</key>\n"
"\t\t<dict>\n"
"\t\t\t<key>IOVirtioBlk</key>\n"
"\t\t\t<dict>\n"
"\t\t\t\t<key>IOClass</key>\n"
"\t\t\t\t<string>IOVirtioBlk</string>\n"
"\t\t\t\t<key>IOProviderClass</key>\n"
"\t\t\t\t<string>IOResources</string>\n"
"\t\t\t\t<key>IOMatchCategory</key>\n"
"\t\t\t\t<string>IOVirtioBlk</string>\n"
"\t\t\t\t<key>IOProbeScore</key>\n"
"\t\t\t\t<integer>1000</integer>\n"
"\t\t\t</dict>\n"
"\t\t</dict>\n"
"\t</dict>\n"
"\t<dict>\n"
"\t\t<key>IOKitPersonalities</key>\n"
"\t\t<dict>\n"
"\t\t\t<key>IOBlockStorageDriver</key>\n"
"\t\t\t<dict>\n"
"\t\t\t\t<key>IOClass</key>\n"
"\t\t\t\t<string>IOBlockStorageDriver</string>\n"
"\t\t\t\t<key>IOPropertyMatch</key>\n"
"\t\t\t\t<dict>\n"
"\t\t\t\t\t<key>device-type</key>\n"
"\t\t\t\t\t<string>Generic</string>\n"
"\t\t\t\t</dict>\n"
"\t\t\t\t<key>IOProviderClass</key>\n"
"\t\t\t\t<string>IOBlockStorageDevice</string>\n"
"\t\t\t</dict>\n"
"\t\t\t<key>IOFDiskPartitionScheme</key>\n"
"\t\t\t<dict>\n"
"\t\t\t\t<key>Content Mask</key>\n"
"\t\t\t\t<string>FDisk_partition_scheme</string>\n"
"\t\t\t\t<key>IOClass</key>\n"
"\t\t\t\t<string>IOFDiskPartitionScheme</string>\n"
"\t\t\t\t<key>IOMatchCategory</key>\n"
"\t\t\t\t<string>IOStorage</string>\n"
"\t\t\t\t<key>IOProbeScore</key>\n"
"\t\t\t\t<integer>3000</integer>\n"
"\t\t\t\t<key>IOPropertyMatch</key>\n"
"\t\t\t\t<dict>\n"
"\t\t\t\t\t<key>Whole</key>\n"
"\t\t\t\t\t<true/>\n"
"\t\t\t\t</dict>\n"
"\t\t\t\t<key>IOProviderClass</key>\n"
"\t\t\t\t<string>IOMedia</string>\n"
"\t\t\t</dict>\n"
"\t\t\t<key>IOGUIDPartitionScheme</key>\n"
"\t\t\t<dict>\n"
"\t\t\t\t<key>Content Mask</key>\n"
"\t\t\t\t<string>GUID_partition_scheme</string>\n"
"\t\t\t\t<key>IOClass</key>\n"
"\t\t\t\t<string>IOGUIDPartitionScheme</string>\n"
"\t\t\t\t<key>IOMatchCategory</key>\n"
"\t\t\t\t<string>IOStorage</string>\n"
"\t\t\t\t<key>IOProbeScore</key>\n"
"\t\t\t\t<integer>4000</integer>\n"
"\t\t\t\t<key>IOPropertyMatch</key>\n"
"\t\t\t\t<dict>\n"
"\t\t\t\t\t<key>Whole</key>\n"
"\t\t\t\t\t<true/>\n"
"\t\t\t\t</dict>\n"
"\t\t\t\t<key>IOProviderClass</key>\n"
"\t\t\t\t<string>IOMedia</string>\n"
"\t\t\t</dict>\n"
"\t\t\t<key>IOMediaBSDClient</key>\n"
"\t\t\t<dict>\n"
"\t\t\t\t<key>IOClass</key>\n"
"\t\t\t\t<string>IOMediaBSDClient</string>\n"
"\t\t\t\t<key>IOMatchCategory</key>\n"
"\t\t\t\t<string>IOMediaBSDClient</string>\n"
"\t\t\t\t<key>IOProbeScore</key>\n"
"\t\t\t\t<integer>30000</integer>\n"
"\t\t\t\t<key>IOProviderClass</key>\n"
"\t\t\t\t<string>IOMedia</string>\n"
"\t\t\t\t<key>IOResourceMatch</key>\n"
"\t\t\t\t<string>IOBSD</string>\n"
"\t\t\t</dict>\n"
"\t\t</dict>\n"
"\t</dict>\n"
"</array>\n"
"</plist>\n";
