iokit_c_sources = files(
    'Kernel/IORTC/IOPL031RTCBuiltinInfo.c',
    'Kernel/IOStringFuncs.c',
)
iokit_cpp_sources = files(
    'Kernel/IOLib.cpp',
    'Kernel/IOLocks.cpp',
    'Kernel/IOConditionLock.cpp',
    'Kernel/IOStartIOKit.cpp',
    'Kernel/IORTC/IOPL031RTC.cpp',
    'Kernel/IOStorage/IOVirtioBlk.cpp',
    'Kernel/IODeviceTreeSupport.cpp',
    'Kernel/IORegistryEntry.cpp',
    'Kernel/IOService.cpp',
    'Kernel/IOServicePM.cpp',
    'Kernel/IOPMinformee.cpp',
    'Kernel/IOPMinformeeList.cpp',
    'Kernel/IOPMPowerStateQueue.cpp',
    'Kernel/IOCatalogue.cpp',
    'Kernel/IOPMPowerSource.cpp',
    'Kernel/IOPMPowerSourceList.cpp',
    'Kernel/IOPMGR.cpp',
    'Kernel/IOPolledInterface.cpp',
    'Kernel/IOWorkLoop.cpp',
    'Kernel/IOEventSource.cpp',
    'Kernel/IOInterruptEventSource.cpp',
    'Kernel/IOCommandGate.cpp',
    'Kernel/IOCommand.cpp',
    'Kernel/IOCommandPool.cpp',
    'Kernel/IOCommandQueue.cpp',
    'Kernel/IODMAEventSource.cpp',
    'Kernel/IOFilterInterruptEventSource.cpp',
    'Kernel/IOTimerEventSource.cpp',
    'Kernel/IOBufferMemoryDescriptor.cpp',
    'Kernel/IODMACommand.cpp',
    'Kernel/IODeviceMemory.cpp',
    'Kernel/IOInterleavedMemoryDescriptor.cpp',
    'Kernel/IOMapper.cpp',
    'Kernel/IOMemoryCursor.cpp',
    'Kernel/IOMemoryDescriptor.cpp',
    'Kernel/IOMultiMemoryDescriptor.cpp',
    'Kernel/IORangeAllocator.cpp',
    'Kernel/IOSubMemoryDescriptor.cpp',
    'Kernel/IOGuardPageMemoryDescriptor.cpp',
    'Kernel/IOPlatformExpert.cpp',
    'Kernel/IOPlatformIO.cpp',
    'Kernel/IOCPU.cpp',
    'Kernel/IOPlatformActions.cpp',
    'Kernel/IONVRAM.cpp',
    'Kernel/IOExtensiblePaniclog.cpp',
    'Kernel/IODMAController.cpp',
    'Kernel/IOInterruptController.cpp',
    'Kernel/PassthruInterruptController.cpp',
    'Kernel/IOUserClient.cpp',
    'Kernel/IOKitDebug.cpp',
    'Kernel/IODataQueue.cpp',
    'Kernel/IOSharedDataQueue.cpp',
    'Kernel/IOCircularDataQueue.cpp',
    'Kernel/IOStatistics.cpp',
    'Kernel/IOInterruptAccounting.cpp',
    'Kernel/IOReporter.cpp',
    'Kernel/IOSimpleReporter.cpp',
    'Kernel/IOStateReporter.cpp',
    'Kernel/IOHistogramReporter.cpp',
    'Kernel/IOReportLegend.cpp',
    'Kernel/IORTC.cpp',
    'Kernel/IOUserServer.cpp',
    'Kernel/IOProviderPropertyMerger.cpp',
    'KernelConfigTables.cpp',
    'bsddev/IOKitBSDInit.cpp',
    'bsddev/DINetBootHook.cpp',
    'Kernel/RootDomainUserClient.cpp',
    'Kernel/IOPowerConnection.cpp',
    'Families/IOSystemManagement/IOWatchDogTimer.cpp',
    'Kernel/IOPerfControl.cpp',
    'Kernel/IOWorkloadConfig.cpp',
    'bsddev/skywalk/IOSkywalkSupport.cpp',
    'Exclaves/Exclaves.cpp',
    'Families/IONVRAM/IONVRAMController.cpp',
    'Kernel/IOPMrootDomain.cpp',
    'Kernel/arm/AppleARMSMP.cpp',
    'Kernel/arm/OSSARMCPU.cpp',
)

iokit_cflags = comp_cflags['iokit'] + c_args
iokit_cxxflags = comp_cflags['iokit'] + cxx_args

xnu_iokit = static_library(
    'xnu_iokit',
    iokit_c_sources + iokit_cpp_sources + gen_order,
    c_args: iokit_cflags,
    cpp_args: iokit_cxxflags,
    kwargs: lib_kwargs,
)

xnu_iokit_driverkit = static_library(
    'xnu_iokit_driverkit',
    iig_c + gen_order,
    c_args: iokit_cflags,
    cpp_args: iokit_cxxflags,
    kwargs: lib_kwargs,
)

kernel_libs += [xnu_iokit, xnu_iokit_driverkit]
